
import Head from 'next/head'
import Image from 'next/image'
import styles from '../../styles/Home.module.css'

import WorkIntro from '../../components/WorkIntro'
// import imgWork from "../../img/developerdao.png"
import ExternalLink from "../../components/ExternalLink";
import BackButton from "../../components/backButton";


import imgWork2 from "../../img/44.png"
import imgWork3 from "../../img/42f3.png"
import imgWork4 from "../../img/4343.png"
import imgWork5 from "../../img/Body  2 Dark (After launching).png"
import imgWork6 from "../../img/develight.png"
import ProjectNavigation from '../../components/ProjectNavigation';


import img1 from "../../img/developerdaofolder/fasdfasd.jpeg";


const DeveloperDAO = () => {
    return (
        <div className={styles.container}>
            <Head>
            <title>DeveloperDAO Website  Mohamed Sadiq</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
            </Head>
        <main>
        <div className="container">
            <BackButton href="/projects" />
            <div className="inner_container">
               <div className="project_title">
              <h1 className="text-black text-lg"> DeeveloperDAO Official Website</h1>
              <p className="text-base">In a mission to accelerate the education and impact of a new wave of web3 builders. <span className="dateProject">- Jun 2023 </span></p>
            </div>
                {/* <WorkIntro title={"DeveloperDao"} link={"/projects/developerdao"} backHref={"/projects"} /> */}
                <div className="blog_photo inner_blog work_intro_image">
              <Image
                src={img1}
                alt="Picture of the author"
                objectFit="cover"
                layout="fill"
                objectPosition="center"
                placeholder="blur"
                quality={100}
              />
            </div>
            
            <h2 className='mt-6'>Project Overview</h2>
             <div className="flex flex-col sm:flex-row justify-between items-start sm:items-center gap-4 pb-6 pt-4">
                            <ExternalLink
                href="https://www.developerdao.com/"
                className='text-[#000] underline decoration-dotted  underline-offset-2 transition-colors duration-200 group-hover:decoration-current'
              >
                Visit Live 
              </ExternalLink>
                            <div className="flex flex-wrap gap-2">
                                {['DAOs', 'Web3', 'UI/UX'].map((tag, index) => (
                                    <span key={index} className="bg-[#f6f6f6] border border-[#f0f0f0] text-black text-sm px-3 py-1.5 rounded-xl whitespace-nowrap">
                                        {tag}
                                    </span>
                                ))}
                            </div>
                        </div>
            <p>
              Developer DAO was one of the first—and most impactful—DAOs I joined in the web3 space. Before that, I was simply intrigued by web3: privacy, decentralization, and the possibilities for the future. I wanted to be someone who helped build that future, not just watch it unfold. <br />Through Developer DAO, I’ve had the chance to collaborate with talented people around the world and be part of a generous, forward‑thinking community.</p>
            <h2 className='mt-10 mb-6'>My Contributions</h2>
            <p>
              It was important for the DAO to establish an official presence to attract potential partnerships and new members. We designed the website to meet that goal: simple, direct, and aligned with the spirit of innovation, intelligence, and adventure. I led the UI and UX design for this project, ensuring the experience was clear, accessible, and true to our mission.
            </p>
           
           
           
          
            {/* <div className="blog_photo inner_blog work_intro_image">
              <Image
                src={img3}
                alt="Picture of the author"
                objectFit="cover"
                layout="fill"
                objectPosition="center"
                placeholder="blur"
                quality={100}
              />
            </div>
            <span className="project_img_des">( An overview of the website.) </span> */}

          
            
            
            </div> 
             {/* Project Navigation */}
                      <div className="container mx-auto px-4 py-8">
                        <ProjectNavigation />
                      </div>
        </div>
        </main>
        </div>
    )
}
export default DeveloperDAO

const data = {
    projectOverview:"Project Overview",
    projectOverviewPara:"Developer DAO is a DAO that exists to accelerate the education and impact of a new wave of web3 builders. The website was among the priorities for the DAO, because of its importance in bringing in new partners and sponsors",
    myContributions:"My Contributions",
    myContributionsPara:"I was the champion of the project on the design side. The existing website did not represent the DAO, the design was so simple, and it did not deliver what it should have been delivering, first step was to analyze the flow and overall aesthetic appeal of the website and figure out the direction that we should take. After that, my job was to simplify the process as much as possible and make it intuitive for the users, as well as improve the visual appeal of the entire site"
}