import Head from "next/head";
import Image from "next/image";
import styles from "../../styles/Home.module.css";
import BackButton from '../../components/backButton'
import ExternalLink from "../../components/ExternalLink";

import WorkIntro from "../../components/WorkIntro";
import imgWork from "../../img/developerdaofm.png";
import img0 from "../../img/developerdaofmfolder/image 2.png";
import img1 from "../../img/developerdaofmfolder/Instagram post - 14.png";
import img2 from "../../img/developerdaofmfolder/Instagram post - 13.png";
import img3 from "../../img/developerdaofmfolder/Dribbble shot HD - 7.png";
import img4 from "../../img/developerdaofmfolder/Instagram post - 9.png";
import img5 from "../../img/developerdaofmfolder/Instagram post - 10.png";
import img6 from "../../img/developerdaofmfolder/Instagram post - 16.png";
import img7 from "../../img/developerdaofmfolder/Instagram post - 17.png";
import ProjectNavigation from '../../components/ProjectNavigation';

const DeveloperDAO: React.FC = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>DeveloperDAO FM</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="container ">
        <BackButton href="/projects" />
          <div className="inner_container_project_parent inner_container inner_container_mobile">
         
            <h1 className="text-black text-lg">DeveloperDAO FM</h1>
            <p className="text-base">
              A place where you listen to music while building cool stuff.{" "}
              <span className="dateProject">- Jul 2022 </span>
            </p>

            <Image
              src={imgWork}
              alt="Picture of the author"
              objectFit="cover"
              // layout="fill"
              objectPosition="center"
              placeholder="blur"
              quality={100}
              className="rounded-xl block mt-4"
            />

            <h2 className="text-slate-950">Project Overview</h2>
            <div className="flex flex-col sm:flex-row justify-between items-start sm:items-center gap-4 pb-6 pt-4">
              <ExternalLink
                href="https://developer-dao-fm.vercel.app/"
                className="text-[#000] underline decoration-dotted underline-offset-2 transition-colors duration-200 group-hover:decoration-current w-fit"
              >
                Visit Live
              </ExternalLink>
              <div className="flex flex-wrap gap-2 w-full sm:w-auto">
                {['DeveloperDAO', 'Music', 'Web3'].map((tag, index) => (
                  <span 
                    key={index} 
                    className="bg-[#f6f6f6] border border-[#f0f0f0] text-black text-sm px-3 py-1.5 rounded-xl whitespace-nowrap"
                  >
                    {tag}
                  </span>
                ))}
              </div>
            </div>
            <p>
              When I initially joined DeveloperDAO, my excitement to contribute
              to the DAO's projects was palpable. One standout project that
              captured my interest was the inception of DeveloperDAO Fm. This
              website aimed to provide coders with an enriched experience,
              allowing them to code while enjoying the soothing accompaniment of
              Lo-Fi music. <br /> <br />
              Beyond its musical offerings, the platform boasted a Pomodoro
              technique-based timer and a seamless channel-switching feature,
              enhancing the coding environment.
            </p>
            <h2>My Contributions</h2>
            <p>
              Delving into my role within this project, I eagerly embraced the
              opportunity to craft an immersive user experience. The heart of
              the experience was encapsulated in the ingeniously simple yet
              functionally profound logo of DeveloperDAO. To infuse an emotional
              incentive.
            </p>

            <Image
              src={img0}
              alt="Picture of the author"
              objectFit="cover"
              // layout="fill"
              objectPosition="center"
              placeholder="blur"
              quality={100}
              className="rounded-xl block mt-4"
            />

            <span className="project_img_des">
              (These were the first attempts to discover the logo's potential, I
              shared this design on <a target="_blank" href="">my X account.</a>){" "}
            </span>
            <p>
              I designed the logo's interactions. A noteworthy feature was the
              logo's dynamic response to user actions – clicking the play
              button prompted the logo's face to break into a cheerful smile,
              while pausing the music led to the logo's smile fading away. This
              nuanced interaction was poised to delight users and accentuate
              their engagement.
            </p>

            <Image
              src={img6}
              alt="Picture of the author"
              objectFit="cover"
              // layout="fill"
              objectPosition="center"
              placeholder="blur"
              quality={100}
              className="rounded-xl block mt-4"
            />

            <span className="project_img_des">(The Play and the Pause modes) </span>

            <Image
              src={img7}
              alt="Picture of the author"
              objectFit="cover"
              // layout="fill"
              objectPosition="center"
              placeholder="blur"
              quality={100}
              className="rounded-xl block mt-4"
            />

            <span className="project_img_des">
              (Closer look at the Play and the Pause buttons.){" "}
            </span>

            <Image
              src={img2}
              alt="Picture of the author"
              objectFit="cover"
              // layout="fill"
              objectPosition="center"
              placeholder="blur"
              quality={100}
              className="rounded-xl block mt-4"
            />

            <span className="project_img_des">
              (This is the music icon, This is where you can switch between music
              channels)
            </span>

            <Image
              src={img3}
              alt="Picture of the author"
              objectFit="cover"
              // layout="fill"
              objectPosition="center"
              placeholder="blur"
              quality={100}
              className="rounded-xl block mt-4"
            />

            <span className="project_img_des">( An overview of the website.) </span>

            {/* <TwitterTweetEmbed tweetId="1482080639159517184" /> */}
            {/* <blockquote class="twitter-tweet"><p lang="en" dir="ltr">Three Moods. <a href="https://t.co/jnIEoMJeCD">pic.twitter.com/jnIEoMJeCD</a></p>&mdash; Mohamed Sadiq (@sadiq_moo) <a href="https://twitter.com/sadiq_moo/status/1482080639159517184?ref_src=twsrc%5Etfw">January 14, 2022</a></blockquote>
            <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script> */}

            <h1>Product hunt's comments</h1>
            <div className="blog_photo inner_blog work_intro_image">
              <Image
                src={img4}
                alt="Picture of the author"
                objectFit="cover"
                layout="fill"
                objectPosition="center"
                placeholder="blur"
                quality={100}
              />
            </div>
            <span className="project_img_des">
              ( Product hunt's comments){" "}
            </span>
            <div className="blog_photo inner_blog work_intro_image">
              <Image
                src={img5}
                alt="Picture of the author"
                objectFit="cover"
                layout="fill"
                objectPosition="center"
                placeholder="blur"
                quality={100}
              />
            </div>
            <span className="project_img_des">
              (Product Hunt's email about featuring developerDAO FM in their
              newsletter.){" "}
            </span>
          </div>
          
          {/* Project Navigation */}
          <div className="container mx-auto px-4 py-8">
            <ProjectNavigation />
          </div>
          
        </div>
      </main>
    </div>
  );
};

export default DeveloperDAO;

interface Data {
  projectOverview: string;
  projectOverviewPara: string;
  myContributions: string;
  myContributionsPara: string;
}

const data: Data = {
  projectOverview: "Project Overview",
  projectOverviewPara:
    "Developer DAO is a DAO that exists to accelerate the education and impact of a new wave of web3 builders. The website was among the priorities for the DAO, because of its importance in bringing in new partners and sponsors",
  myContributions: "My Contributions",
  myContributionsPara:
    "I was the champion of the project on the design side. The existing website did not represent the DAO, the design was so simple, and it did not deliver what it should have been delivering, first step was to analyze the flow and overall aesthetic appeal of the website and figure out the direction that we should take. After that, my job was to simplify the process as much as possible and make it intuitive for the users, as well as improve the visual appeal of the entire site",
};
