
import Head from 'next/head'
import Image from 'next/image'
import styles from '../../styles/Home.module.css'

import WorkIntro from '../../components/WorkIntro'
// import imgWork from "../../img/developerdao.png"


import imgWork2 from "../../img/44.png"
import imgWork3 from "../../img/42f3.png"
import imgWork4 from "../../img/4343.png"
import imgWork5 from "../../img/Body  2 Dark (After launching).png"
import imgWork6 from "../../img/develight.png"


import img1 from "../../img/developerdaofolder/fasdfasd.jpeg";


const DeveloperDAO = () => {
    return (
        <div className={styles.container}>
            <Head>
            <title>DeveloperDAO Website | Mohamed Sadiq</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
            </Head>
        <main>
        <div className="container">
            <div className="inner_container">
             
                <WorkIntro title={"DeveloperDao"} link={"/projects/developerdao"}/>
                <div className="blog_photo inner_blog work_intro_image">
              <Image
                src={img1}
                alt="Picture of the author"
                objectFit="cover"
                layout="fill"
                objectPosition="center"
                placeholder="blur"
                quality={100}
              />
            </div>
            
            <h2>Project Overview</h2>
            <p>
              When I initially joined DeveloperDAO, my excitement to contribute
              to the DAO's projects was palpable. One standout project that
              captured my interest was the inception of DeveloperDAO Fm. This
              website aimed to provide coders with an enriched experience,
              allowing them to code while enjoying the soothing accompaniment of
              Lo-Fi music. <br /> <br /> Beyond its musical offerings, the
              platform boasted a Pomodoro technique-based timer and a seamless
              channel-switching feature, enhancing the coding environment.
            </p>
            <h2>My Contributions</h2>
            <p>
              Delving into my role within this project, I eagerly embraced the
              opportunity to craft an immersive user experience. The heart of
              the experience was encapsulated in the ingeniously simple yet
              functionally profound logo of DeveloperDAO. To infuse an emotional
              incentive.
            </p>
           
            <p>
              I strategically designed the logo's interactions. A noteworthy
              feature was the logo's dynamic response to user actions – clicking
              the play button prompted the logo's face to break into a cheerful
              smile, while pausing the music led to the logo's smile fading
              away. This nuanced interaction was poised to delight users and
              accentuate their engagement.
            </p>
           
          
            {/* <div className="blog_photo inner_blog work_intro_image">
              <Image
                src={img3}
                alt="Picture of the author"
                objectFit="cover"
                layout="fill"
                objectPosition="center"
                placeholder="blur"
                quality={100}
              />
            </div>
            <span className="project_img_des">( An overview of the website.) </span> */}

          
            <h2>Reflection —</h2>
            <p>
              Sharing my creation with the community brought forth an outpouring
              of positive feedback, especially from fellow DAO members. This
              enthusiastic reception fostered a sense of unity, akin to
              belonging to an exclusive club, with the positive energy
              resonating outward. Emboldened by this initial response, I took a
              bold step and showcased DeveloperDAO Fm on Product Hunt, a
              platform known for spotlighting innovative products. <br /> <br />{" "}
              The outcome was nothing short of remarkable – DeveloperDAO Fm
              rapidly ascended to secure a position as one of the platform's
              top-rated products. The pinnacle achievement of this project,
              however, lay in its profound impact on the DAO's brand awareness.
              By seamlessly blending practical coding utilities with an
              immersive musical experience, DeveloperDAO Fm not only
              accomplished its intended objectives but also reverberated deeply
              within the coding community. This project illuminated the
              potential of creativity and innovation in fostering community
              bonds while concurrently achieving strategic milestones. With this
              reflection, <br /> <br />
              I've come to appreciate how a single project can be a catalyst for
              both personal growth and broader community engagement. The fusion
              of creative thinking and strategic execution emerged as a powerful
              force in realizing meaningful goals.
            </p>
            <div className="projects_link">
              <h3>Links</h3>
              <ul>
               
                <a href="https://developerdao.com">
                  <li>DeveloperDAO website</li>
                </a>
              </ul>
              <h3>Tools I Used</h3>
              <ul>
              <a href="">
                  <li> Figma</li>
                </a>
               
              </ul>
            </div>
          
            </div> 
        </div>
        </main>
        </div>
    )
}
export default DeveloperDAO

const data = {
    projectOverview:"Project Overview",
    projectOverviewPara:"Developer DAO is a DAO that exists to accelerate the education and impact of a new wave of web3 builders. The website was among the priorities for the DAO, because of its importance in bringing in new partners and sponsors",
    myContributions:"My Contributions",
    myContributionsPara:"I was the champion of the project on the design side. The existing website did not represent the DAO, the design was so simple, and it did not deliver what it should have been delivering, first step was to analyze the flow and overall aesthetic appeal of the website and figure out the direction that we should take. After that, my job was to simplify the process as much as possible and make it intuitive for the users, as well as improve the visual appeal of the entire site"
}