import Head from "next/head";
import Image from "next/image";
import styles from "../../styles/Home.module.css";
import { TwitterTweetEmbed } from "react-twitter-embed";

import WorkIntro from "../../components/WorkIntro";
import imgWork from "../../img/developerdaofm.png";
import img0 from "../../img/developerdaofmfolder/image 2.png";
import img1 from "../../img/developerdaofmfolder/Instagram post - 14.png";
import img2 from "../../img/developerdaofmfolder/Instagram post - 13.png";
import img3 from "../../img/developerdaofmfolder/Dribbble shot HD - 7.png";
import img4 from "../../img/developerdaofmfolder/Instagram post - 9.png";
import img5 from "../../img/developerdaofmfolder/Instagram post - 10.png";
import img6 from "../../img/developerdaofmfolder/Instagram post - 16.png";
import img7 from "../../img/developerdaofmfolder/Instagram post - 17.png";
const DeveloperDAO = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>DeveloperDAO FM Website | Mohamed Sadiq</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="container">
          <div className="inner_container">
            <WorkIntro
              title={"DeveloperDAO FM"}
              link={"https://www.developerdaofm.com/"}
            />
            <h1>DeveloperDAO FM</h1>
            <div className="blog_photo inner_blog work_intro_image">
              <Image
                src={imgWork}
                alt="Picture of the author"
                objectFit="cover"
                layout="fill"
                objectPosition="center"
                placeholder="blur"
                quality={100}
              />
            </div>
            
            <h2>Project Overview</h2>
            <p>
              When I initially joined DeveloperDAO, my excitement to contribute
              to the DAO's projects was palpable. One standout project that
              captured my interest was the inception of DeveloperDAO Fm. This
              website aimed to provide coders with an enriched experience,
              allowing them to code while enjoying the soothing accompaniment of
              Lo-Fi music. <br /> <br /> Beyond its musical offerings, the
              platform boasted a Pomodoro technique-based timer and a seamless
              channel-switching feature, enhancing the coding environment.
            </p>
            <h2>My Contributions</h2>
            <p>
              Delving into my role within this project, I eagerly embraced the
              opportunity to craft an immersive user experience. The heart of
              the experience was encapsulated in the ingeniously simple yet
              functionally profound logo of DeveloperDAO. To infuse an emotional
              incentive.
            </p>
            <div className="blog_photo inner_blog ">
              <Image
                src={img0}
                alt="Picture of the author"
                objectFit="cover"
                layout="fill"
                objectPosition="center"
                placeholder="blur"
                quality={100}
              />
            </div>
            <span className="project_img_des">(These were the first attempts to discover the logo's potential, I shared this design on <a target="_blink" href="">my X account.</a>) </span>
            <p>
              I strategically designed the logo's interactions. A noteworthy
              feature was the logo's dynamic response to user actions – clicking
              the play button prompted the logo's face to break into a cheerful
              smile, while pausing the music led to the logo's smile fading
              away. This nuanced interaction was poised to delight users and
              accentuate their engagement.
            </p>
            <div className="blog_photo inner_blog work_intro_image">
              <Image
                src={img6}
                alt="Picture of the author"
                objectFit="cover"
                layout="fill"
                objectPosition="center"
                placeholder="blur"
                quality={100}
              />
            </div>
            <span className="project_img_des">(The Play and the Pause modes) </span>
            <div className="blog_photo inner_blog work_intro_image">
              <Image
                src={img7}
                alt="Picture of the author"
                objectFit="cover"
                layout="fill"
                objectPosition="center"
                placeholder="blur"
                quality={100}
              />
            </div>
            <span className="project_img_des">(Closer look at the Play and the Pause buttons.) </span>
            
            <div className="blog_photo inner_blog work_intro_image">
              <Image
                src={img2}
                alt="Picture of the author"
                objectFit="cover"
                layout="fill"
                objectPosition="center"
                placeholder="blur"
                quality={100}
              />
            </div>
            <span className="project_img_des">(This is the music icon, This is where you can switch between music channels)</span>
            <div className="blog_photo inner_blog work_intro_image">
              <Image
                src={img3}
                alt="Picture of the author"
                objectFit="cover"
                layout="fill"
                objectPosition="center"
                placeholder="blur"
                quality={100}
              />
            </div>
            <span className="project_img_des">( An overview of the website.) </span>

            {/* <TwitterTweetEmbed tweetId="1482080639159517184" /> */}
            {/* <blockquote class="twitter-tweet"><p lang="en" dir="ltr">Three Moods. <a href="https://t.co/jnIEoMJeCD">pic.twitter.com/jnIEoMJeCD</a></p>&mdash; Mohamed Sadiq (@sadiq_moo) <a href="https://twitter.com/sadiq_moo/status/1482080639159517184?ref_src=twsrc%5Etfw">January 14, 2022</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script> */}
            <h2>Reflection —</h2>
            <p>
              Sharing my creation with the community brought forth an outpouring
              of positive feedback, especially from fellow DAO members. This
              enthusiastic reception fostered a sense of unity, akin to
              belonging to an exclusive club, with the positive energy
              resonating outward. Emboldened by this initial response, I took a
              bold step and showcased DeveloperDAO Fm on Product Hunt, a
              platform known for spotlighting innovative products. <br /> <br />{" "}
              The outcome was nothing short of remarkable – DeveloperDAO Fm
              rapidly ascended to secure a position as one of the platform's
              top-rated products. The pinnacle achievement of this project,
              however, lay in its profound impact on the DAO's brand awareness.
              By seamlessly blending practical coding utilities with an
              immersive musical experience, DeveloperDAO Fm not only
              accomplished its intended objectives but also reverberated deeply
              within the coding community. This project illuminated the
              potential of creativity and innovation in fostering community
              bonds while concurrently achieving strategic milestones. With this
              reflection, <br /> <br />
              I've come to appreciate how a single project can be a catalyst for
              both personal growth and broader community engagement. The fusion
              of creative thinking and strategic execution emerged as a powerful
              force in realizing meaningful goals.
            </p>
            <h1>Product hunt's comments</h1>
            <div className="blog_photo inner_blog work_intro_image">
              <Image
                src={img4}
                alt="Picture of the author"
                objectFit="cover"
                layout="fill"
                objectPosition="center"
                placeholder="blur"
                quality={100}
              />
            </div>
            <span className="project_img_des">( Product hunt's comments) </span>
            <div className="blog_photo inner_blog work_intro_image">
              <Image
                src={img5}
                alt="Picture of the author"
                objectFit="cover"
                layout="fill"
                objectPosition="center"
                placeholder="blur"
                quality={100}
              />
            </div>
            <span className="project_img_des">(Product Hunt's email about featuring developerDAO FM in their newsletter.) </span>
            <div className="projects_link">
              <h3>Links</h3>
              <ul>
                <a href="https://www.developerdaofm.com/">
                  <li>DeveloperDAO FM Website</li>
                </a>
                <a href="https://www.producthunt.com/products/developer-dao-fm">
                  <li>DeveloperDAO FM on ProductHunt</li>
                </a>
                <a href="https://developerdao.com">
                  <li>DeveloperDAO website</li>
                </a>
              </ul>
              <h3>Tools I Used</h3>
              <ul>
              <a href="">
                  <li> Figma</li>
                </a>
                <a href="">
                  <li> Next.js</li>
                </a>
                <a href="">
                  <li>Framer Motion</li>
                </a>
                <a href="">
                  <li>VS Code</li>
                </a>
                <a href="">
                  <li>Arc Browser</li>
                </a>
              </ul>
            </div>
          </div>
        </div>
      </main>
    </div>
  );
};
export default DeveloperDAO;

const data = {
  projectOverview: "Project Overview",
  projectOverviewPara:
    "Developer DAO is a DAO that exists to accelerate the education and impact of a new wave of web3 builders. The website was among the priorities for the DAO, because of its importance in bringing in new partners and sponsors",
  myContributions: "My Contributions",
  myContributionsPara:
    "I was the champion of the project on the design side. The existing website did not represent the DAO, the design was so simple, and it did not deliver what it should have been delivering, first step was to analyze the flow and overall aesthetic appeal of the website and figure out the direction that we should take. After that, my job was to simplify the process as much as possible and make it intuitive for the users, as well as improve the visual appeal of the entire site",
};
