
import Head from 'next/head'
import Image from 'next/image'
import styles from '../../styles/Home.module.css'

import WorkIntro from '../../components/WorkIntro'
// import imgWork from "../../img/developerdao.png"
import imgWork from "../../img/fasdfasd.jpeg"

import imgWork2 from "../../img/44.png"
import imgWork3 from "../../img/42f3.png"
import imgWork4 from "../../img/4343.png"
import imgWork5 from "../../img/Body  2 Dark (After launching).png"
import imgWork6 from "../../img/develight.png"

const DeveloperDAO = () => {
    return (
        <div className={styles.container}>
            <Head>
            <title>DeveloperDAO Website | Mohamed Sadiq</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
            </Head>
        <main>
        <div className="container">
            <div className="inner_container">
             
                <WorkIntro title={"DeveloperDao"} link={"/projects/developerdao"}/>
                <h1>Developer DAO website</h1>
                <div className="blog_photo inner_blog work_intro_image">
                <Image
                    src={imgWork}
                    alt="Picture of the author"
                    objectFit='cover'
                    layout='fill'
                    objectPosition="center"
                    placeholder="blur"
                    quality={100}
                />
            </div>
          
           <div className='content_work'>
           {/* <h2>Role</h2>
            <p>UI/UX - Product Design</p> */}

           <h2>Project Overview</h2>
            <p>Developer DAO is a DAO that exists to accelerate the education and impact of a new wave of web3 builders. The website was among the priorities for the DAO, because of its importance in bringing in new partners and sponsors</p>
           <div className=''>
            <div className=''>
                <h2>My Contributions</h2>
                <p>I was the champion of the project on the design side.The existing website did not represent the DAO, the design was so simple, and it did not deliver what it should have been delivering, first step was to analyze the flow and overall aesthetic appeal of the website and figure out the direction that we should take. After that, my job was to simplify the process as much as possible and make it intuitive for the users, as well as improve the visual appeal of the entire site.</p>
            </div>
            <div className=''>
            {/* <h2>My Role</h2>
                <ul>
                    <li>UI/UX</li>
                <li>Product Design</li>
                </ul> */}
            </div>
           </div>
           </div>
            {/* <div className="blog_photo inner_blog work_intro_image">
                <Image
                    src={imgWork2}
                    alt="Picture of the author"
                    objectFit='cover'
                    layout='fill'
                    objectPosition="center"
                    placeholder="blur"
                    quality={100}
                />
            </div>
            <div className="blog_photo inner_blog work_intro_image">
                <Image
                    src={imgWork6}
                    alt="Picture of the author"
                    objectFit='cover'
                    layout='fill'
                    objectPosition="center"
                    placeholder="blur"
                    quality={100}
                />
            </div> */}
            
             <h2>Reflection —</h2>
            <p>I was the champion of the project on the design side.The existing website did not represent the DAO, the design was so simple, and it did not deliver what it should have been delivering, first step was to analyze the flow and overall aesthetic appeal of the website and figure out the direction that we should take. After that, my job was to simplify the process as much as possible and make it intuitive for the users, as well as improve the visual appeal of the entire site.</p>

            <a href=''>Check out the website</a>
            </div> 
        </div>
        </main>
        </div>
    )
}
export default DeveloperDAO

const data = {
    projectOverview:"Project Overview",
    projectOverviewPara:"Developer DAO is a DAO that exists to accelerate the education and impact of a new wave of web3 builders. The website was among the priorities for the DAO, because of its importance in bringing in new partners and sponsors",
    myContributions:"My Contributions",
    myContributionsPara:"I was the champion of the project on the design side. The existing website did not represent the DAO, the design was so simple, and it did not deliver what it should have been delivering, first step was to analyze the flow and overall aesthetic appeal of the website and figure out the direction that we should take. After that, my job was to simplify the process as much as possible and make it intuitive for the users, as well as improve the visual appeal of the entire site"
}