import Head from 'next/head'
import {useState} from "react"
import Image from 'next/image'
import Link from 'next/link';
// images Wallets
import bag1 from "../../img/558273.jpg"
import bag2 from "../../img/6ZRenz84rh5f9p5a9lD1QA.jpeg"
import bag3 from "../../img/1CYuIeP2bfxgjbdq8NNKgp.jpeg"
import bag4 from "../../img/2IUtBE3GKRrbBraF5UOH5H.jpeg"
import bag5 from "../../img/bdlkh36BmMSbfM49pAvbWZ.jpeg"
import bag6 from "../../img/g7GYDEyvtkjcKMxWp1W04F.jpeg"
import bag7 from "../../img/0016477_xiaomi-mi-computer-monitor-light-bar_511.png"
import bag8 from "../../img/MK2E3_AV1.jpeg"

const Aesthetic = () =>{
    const [table1 , setTable1] = useState(true);
    const [table2 , setTable2] = useState(false);
    const [table3 , setTable3] = useState(false);
    const [table4 , setTable4] = useState(false);
    const [table5 , setTable5] = useState(false);
 
    const switch1 = () => {
     setTable1(true);
     setTable2(false);
     setTable3(false);
     setTable4(false);
     setTable5(false);
    }
    const switch2 = () => {
     setTable1(false);
     setTable2(true);
     setTable3(false);
     setTable4(false);
     setTable5(false);
    }
    const switch3 = () => {
     setTable1(false);
     setTable2(false);
     setTable3(true);
     setTable4(false);
     setTable5(false);
    }
    const switch4 = () => {
     setTable1(false);
     setTable2(false);
     setTable3(false);
     setTable4(true);
     setTable5(false);
    }
    const switch5 = () => {
     setTable1(false);
     setTable2(false);
     setTable3(false);
     setTable4(false);
     setTable5(true);
    }
    return (
        <>
        <Head>
            <title>Aesthetic </title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
      <main>
            <div className="container">
                <div className="inner_container">
                <div className="inner_nav">
                    <span><Link href="/">Home</Link>   &gt; </span>
                    <span><Link href="/oasis">Oasis</Link>  &gt; </span>
                    <span><Link href="/taste/aesthetic">Aesthetic</Link></span>
                </div>
                <h1>Aesthetic</h1>
                    <p>Explore my stylish and practical collection of fashion, accessories, and tech gadgets that will enhance your daily routines and elevate your personal style.</p>
                    <div className="filtter">
                        <ul>
                            <li onClick={ () => switch1()} className={table1 ?  "bottom_line  ": " "}>All</li>
                            <li onClick={ () => switch2()} className={table2 ?  "bottom_line  ": " "}>Fashion</li>
                            <li onClick={ () => switch3()} className={table3 ?  "bottom_line  ": " "}>Tech</li>
                            <div className="fil">
                                {/* <svg width="17" height="17" viewBox="0 0 9 10" fill="none" xmlns="http://www.w3.org/2000/svg">
                                    <path d="M0.0593468 0.237069C-0.0276426 0.386095 -0.015166 0.559994 0.0717367 0.709091L0.0841265 0.721481L3.09002 4.93221V9.68947C3.09002 9.81372 3.16453 9.92549 3.26391 9.97513C3.30116 10 3.3509 10 3.40054 10C3.47506 10 3.53718 9.97513 3.5993 9.92549L5.12707 8.64612C5.20158 8.584 5.23884 8.4971 5.23884 8.4101V4.93221L8.24473 0.721474L8.25712 0.709084C8.34411 0.560059 8.35649 0.38616 8.26951 0.237063C8.18252 0.0880369 8.03348 0.0010409 7.85961 0.0010409H0.456895C0.295395 -0.0113489 0.133903 0.0880303 0.059377 0.237063L0.0593468 0.237069Z" fill="#383838"/>
                                </svg> */}
                            </div>
                        </ul>
                    </div>
                    <div className="trasition_counter">
                    <div className={table1 ?  "trans statesOn" : "trans statesOff "}>
                    <div className='mItv1'>
                        <div className='ripi6'>
                        {all_grid1.map(item => {
              return (
                  <a  key={item} href={item.link} target="_blink">
                      <div key={item.name} className="blocks_aes">
                      <div className="">
                        <div className="img_aes">
                        <Image
                            src={item.img}
                            alt="Picture of the author"
                            objectFit='cover'
                            layout='fill'
                            objectPosition="center"
                            placeholder="blur"
                            quality={100}
                            />
               
                        </div>
                      </div>
                     <div className="dec_aes"> 
                        <h1>{item.name}</h1>
                        
                        <p>{item.description}</p>
                        <button> See</button>
                       
                     </div>
                  </div>
                  </a>
              )
          })}
                        </div>
                        <div className='ripi6'>
                        {all_grid2.map(item => {
              return (
                  <a  key={item} href={item.link} target="_blink">
                      <div key={item.name} className="blocks_aes">
                      <div className="">
                        <div className="img_aes">
                        <Image
                            src={item.img}
                            alt="Picture of the author"
                            objectFit='cover'
                            layout='fill'
                            objectPosition="center"
                            placeholder="blur"
                            quality={100}
                            />
               
                        </div>
                      </div>
                     <div className="dec_aes"> 
                        <h1>{item.name}</h1>
                        
                        <p>{item.description}</p>
                        <button> See </button>
                       
                     </div>
                  </div>
                  </a>
              )
          })}
                        </div>
                    </div>
          <div className="inner_stack">
          
          </div>
          </div>

          <div className={table2 ?  "trans statesOn" : "trans statesOff "}>
                    <div className='mItv1'>
                        <div className='ripi6'>
                        {fashion.map(item => {
              return (
                  <a  key={item} href={item.link} target="_blink">
                      <div key={item.name} className="blocks_aes">
                      <div className="">
                        <div className="img_aes">
                        <Image
                            src={item.img}
                            alt="Picture of the author"
                            objectFit='cover'
                            layout='fill'
                            objectPosition="center"
                            placeholder="blur"
                            quality={100}
                            />
               
                        </div>
                      </div>
                     <div className="dec_aes"> 
                        <h1>{item.name}</h1>
                        
                        <p>{item.description}</p>
                        <button> See</button>
                       
                     </div>
                  </div>
                  </a>
              )
          })}
                        </div>
                        <div className='ripi6'>
                        {fashion2.map(item => {
              return (
                  <a  key={item} href={item.link} target="_blink">
                      <div key={item.name} className="blocks_aes">
                      <div className="">
                        <div className="img_aes">
                        <Image
                            src={item.img}
                            alt="Picture of the author"
                            objectFit='cover'
                            layout='fill'
                            objectPosition="center"
                            placeholder="blur"
                            quality={100}
                            />
               
                        </div>
                      </div>
                     <div className="dec_aes"> 
                        <h1>{item.name}</h1>
                        
                        <p>{item.description}</p>
                        <button> See </button>
                       
                     </div>
                  </div>
                  </a>
              )
          })}
                        </div>
                    </div>
          <div className="inner_stack">
          
          </div>
          </div>
          <div className={table3 ?  "trans statesOn" : "trans statesOff "}>
                    <div className='mItv1'>
                        <div className='ripi6'>
                        {tech1.map(item => {
              return (
                  <a  key={item} href={item.link} target="_blink">
                      <div key={item.name} className="blocks_aes">
                      <div className="">
                        <div className="img_aes">
                        <Image
                            src={item.img}
                            alt="Picture of the author"
                            objectFit='cover'
                            layout='fill'
                            objectPosition="center"
                            placeholder="blur"
                            quality={100}
                            />
               
                        </div>
                      </div>
                     <div className="dec_aes"> 
                        <h1>{item.name}</h1>
                        
                        <p>{item.description}</p>
                        <button> See</button>
                       
                     </div>
                  </div>
                  </a>
              )
          })}
                        </div>
                        <div className='ripi6'>
                        {tech2.map(item => {
              return (
                  <a  key={item} href={item.link} target="_blink">
                      <div key={item.name} className="blocks_aes">
                      <div className="">
                        <div className="img_aes">
                        <Image
                            src={item.img}
                            alt="Picture of the author"
                            objectFit='cover'
                            layout='fill'
                            objectPosition="center"
                            placeholder="blur"
                            quality={100}
                            />
               
                        </div>
                      </div>
                     <div className="dec_aes"> 
                        <h1>{item.name}</h1>
                        
                        <p>{item.description}</p>
                        <button> See </button>
                       
                     </div>
                  </div>
                  </a>
              )
          })}
                        </div>
                   
                    </div>
          
          </div>
          </div>
      
                </div>
            </div>
      </main>
        
        </>
    )
}

export default Aesthetic
const all_grid1 = [
    
    {
        name:"REPRESENT OWNERS CLUB HOODIE - FLAT WHITE",
        img:bag5,
        description:"Flat White slightly oversized fit hoodie in a heavy weight jersey cotton.",
        link:"https://representclo.com/products/represent-owners-club-hoodie-flat-white"
    },
    {
        name:"Hands-on mobile stand",
        img:bag6,
        description:"This mobile holder for your desk grants uninterrupted multitasking with full-screen access to soothe a busy day.",
        link:"https://www.nooe.co/collections/all/products/hands-on-mobile-stand?variant=39408637870273"
    }
    ,
    {
        name:"Gnosis Safe",
        img:bag7,
        description:"Extra Computer Lighting w/o Taking Desktop Space.",
        link:"https://www.mi.com/global/product/mi-computer-monitor-light-bar/"
    },
    {
        name:"Magic Mouse - White Multi-Touch Surface",
        img:bag8,
        description:"Magic Mouse with an optimized foot design that lets it glide smoothly across your desk. ",
        link:"https://www.apple.com/shop/product/MK2E3AM/A/magic-mouse-white-multi-touch-surface"
    }
]

const all_grid2 = [
    {
        name:"Yezzy 500",
        img:bag1,
        description:"The adidas Yeezy 500 was first released in 2018, following the clunky shoe trend....",
        link:"https://news.adidas.com/yeezy-500"
    },
    {
        name:"Blank Sweater - Slate",
        img:bag2,
        description:"Slate sweater with an oversized fit in a heavy weight jersey cotton",
        link:"https://representclo.com/products/blank-sweater-slate"
    },
    {
        name:"Anywhere laptop stand.",
        img:bag3,
        description:"AA perfectly balanced, true to the name- anywhere laptop stand.",
        link:"https://www.nooe.co/collections/all/products/hands-on-mobile-stand?variant=39408637870273"
    },
    {
        name:"SUEDE DESK RUG",
        img:bag4,
        description:"A suede desk mat. Why didn’t anyone else think of that before?",
        link:"https://www.nooe.co/collections/all/products/suede-desk-rug?variant=39409010376897"
    },
  
]

const fashion =  [
    {
        name:"Yezzy 500",
        img:bag1,
        description:"The adidas Yeezy 500 was first released in 2018, following the clunky shoe trend....",
        link:"https://news.adidas.com/yeezy-500"
    },
    {
        name:"Blank Sweater - Slate",
        img:bag2,
        description:"Slate sweater with an oversized fit in a heavy weight jersey cotton",
        link:"https://representclo.com/products/blank-sweater-slate"
    },
   
   
]
const fashion2 =  [
   
    {
        name:"REPRESENT OWNERS CLUB HOODIE - FLAT WHITE",
        img:bag5,
        description:"Flat White slightly oversized fit hoodie in a heavy weight jersey cotton.",
        link:"https://representclo.com/products/represent-owners-club-hoodie-flat-white"
    },
   
]
  
const tech1 =  [
    {
        name:"Anywhere laptop stand.",
        img:bag3,
        description:"AA perfectly balanced, true to the name- anywhere laptop stand.",
        link:"https://www.nooe.co/collections/all/products/hands-on-mobile-stand?variant=39408637870273"
    },
    {
        name:"SUEDE DESK RUG",
        img:bag4,
        description:"A suede desk mat. Why didn’t anyone else think of that before?",
        link:"https://www.nooe.co/collections/all/products/suede-desk-rug?variant=39409010376897"
    },
    {
        name:"Hands-on mobile stand",
        img:bag6,
        description:"This mobile holder for your desk grants uninterrupted multitasking with full-screen access to soothe a busy day.",
        link:"https://www.nooe.co/collections/all/products/hands-on-mobile-stand?variant=39408637870273"
    }
    
]
const tech2 =  [
    
    
    {
        name:"Gnosis Safe",
        img:bag7,
        description:"Extra Computer Lighting w/o Taking Desktop Space.",
        link:"https://www.mi.com/global/product/mi-computer-monitor-light-bar/"
    },
    {
        name:"Magic Mouse - White Multi-Touch Surface",
        img:bag8,
        description:"Magic Mouse with an optimized foot design that lets it glide smoothly across your desk. ",
        link:"https://www.apple.com/shop/product/MK2E3AM/A/magic-mouse-white-multi-touch-surface"
    }
]