

import Head from "next/head"
import { useState } from "react"
import Image from 'next/image'
import Link from 'next/link';
// images Wallets
import book1 from "../../img/Rectangle 256.png"
import book2 from "../../img/Rectangle 257.png"
import book3 from "../../img/download.jpeg"
import book4 from "../../img/the-wisdom-of-life-20.jpg"
import book5 from "../../img/When_Nietzsche_Wept_(novel).jpg"
import book6 from "../../img/81fcWvYdukL._AC_UF1000,1000_QL80_.jpg"
import book7 from "../../img/51tw6UjHpDL._SX330_BO1,204,203,200_.jpg"
import book8 from "../../img/41-z0MNHwKL._SX326_BO1,204,203,200_.jpg"
import book9 from "../../img/41+L96XeERL._SX324_BO1,204,203,200_.jpg"
import book10 from "../../img/21RA2-qTqvL._SX331_BO1,204,203,200_.jpg"
import book11 from "../../img/ThusSpokeZarathustra-01.webp"
import book12 from "../../img/414yS8wldNL._SX320_BO1,204,203,200_.jpg"


const Books = () => {
    const [wallets, setWallet] = useState(true);
    const [dao, setDao] = useState(false);
    const [tools, setTools] = useState(false);

    const switchWallet = () => {
        setWallet(true);
        setDao(false);
        setTools(false);
    }
    const switchDao = () => {
        setDao(true);
        setWallet(false);
        setTools(false)
    }
    const switchTools = () => {
        setTools(true)
        setDao(false);
        setWallet(false);
    }

    return (
        <>
            <Head>
                <title>Books </title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
                <div className="container">
                    <div className="inner_container">
                        <div className="inner_nav">
                            <span><Link href="/">Home</Link>  > </span>
                            <span><Link href="/oasis">Oasis</Link> > </span>
                            <span><Link href="/taste/books">Books</Link> </span>
                        </div>
                        <h1>Books</h1>
                        <p>Here is a list of my books recommendations.</p>
                        <div className="filtter">
                            <ul>
                                <li onClick={() => switchWallet()} className={wallets ? "bottom_line  " : " "}>Design</li>
                                <li onClick={() => switchDao()} className={dao ? "bottom_line  " : " "}>Philosophy</li>
                                <li onClick={() => switchTools()} className={tools ? "bottom_line  " : " "}>Biography</li>
                                <div className="fil">
                                    <svg width="17" height="17" viewBox="0 0 9 10" fill="none" xmlns="http://www.w3.org/2000/svg">
                                        <path d="M0.0593468 0.237069C-0.0276426 0.386095 -0.015166 0.559994 0.0717367 0.709091L0.0841265 0.721481L3.09002 4.93221V9.68947C3.09002 9.81372 3.16453 9.92549 3.26391 9.97513C3.30116 10 3.3509 10 3.40054 10C3.47506 10 3.53718 9.97513 3.5993 9.92549L5.12707 8.64612C5.20158 8.584 5.23884 8.4971 5.23884 8.4101V4.93221L8.24473 0.721474L8.25712 0.709084C8.34411 0.560059 8.35649 0.38616 8.26951 0.237063C8.18252 0.0880369 8.03348 0.0010409 7.85961 0.0010409H0.456895C0.295395 -0.0113489 0.133903 0.0880303 0.059377 0.237063L0.0593468 0.237069Z" fill="#383838" />
                                    </svg>
                                </div>
                            </ul>
                        </div>
                        <div className="inner_blockes">
                            <div className={wallets ? "trans statesOn" : "trans statesOff "}>
                                {wallet.map(item => {
                                    return (
                                        <a key={item} href={item.link} target="_blink">
                                            <div key={item.name} className="block_books">
                                                <div className="block_book_f">
                                                    <div className="block_books_img">
                                                        <Image
                                                            src={item.img}
                                                            alt="Picture of the author"
                                                            objectFit='cover'
                                                            // layout='fill'
                                                            objectPosition="center"
                                                            placeholder="blur"
                                                            quality={100}
                                                        />
                                                    </div>
                                                    <div className="data_des">
                                                        <h2>{item.name}</h2>
                                                        <p>{item.description} </p>
                                                        <span>
                                                            <svg width="35" height="15" viewBox="0 0 35 35" fill="none" xmlns="http://www.w3.org/2000/svg">
                                                                <path d="M33.2126 3.04953L33.2126 22.4767L35 22.4767L35 0.00128174L12.5233 0.00128076L12.5233 1.78628L31.9498 1.78871L-2.56206e-06 33.7356L1.26325 34.9988L33.2126 3.04953Z" fill="#464646" />
                                                            </svg>
                                                        </span>
                                                    </div>
                                                </div>

                                            </div>
                                        </a>

                                    )
                                })}
                            </div>
                            <div className={dao ? "trans statesOn" : "trans statesOff "}>
                                {philosophy.map(item => {
                                    return (
                                        <a key={item} href={item.link} target="_blink">
                                            <div key={item.name} className="block_books">
                                                <div className="block_book_f">
                                                    <div className="block_books_img">
                                                        <Image
                                                            src={item.img}
                                                            alt="Picture of the author"
                                                            objectFit='cover'
                                                            // layout='fill'
                                                            objectPosition="center"
                                                            placeholder="blur"
                                                            quality={100}
                                                        />
                                                    </div>
                                                    <div className="data_des">
                                                        <h2>{item.name}</h2>
                                                        <p>{item.description} </p>
                                                        <span>
                                                            <svg width="35" height="15" viewBox="0 0 35 35" fill="none" xmlns="http://www.w3.org/2000/svg">
                                                                <path d="M33.2126 3.04953L33.2126 22.4767L35 22.4767L35 0.00128174L12.5233 0.00128076L12.5233 1.78628L31.9498 1.78871L-2.56206e-06 33.7356L1.26325 34.9988L33.2126 3.04953Z" fill="#464646" />
                                                            </svg>
                                                        </span>
                                                    </div>
                                                </div>

                                            </div>
                                        </a>

                                    )
                                })}
                            </div>
                            <div className={tools ? "trans statesOn" : "trans statesOff "}>
                                {biography.map(item => {
                                    return (
                                        <a key={item} href={item.link} target="_blink">
                                            <div key={item.name} className="block_books">
                                                <div className="block_book_f">
                                                    <div className="block_books_img">
                                                        <Image
                                                            src={item.img}
                                                            alt="Picture of the author"
                                                            objectFit='cover'
                                                            // layout='fill'
                                                            objectPosition="center"
                                                            placeholder="blur"
                                                            quality={100}
                                                        />
                                                    </div>
                                                    <div className="data_des">
                                                        <h2>{item.name}</h2>
                                                        <p>{item.description} </p>
                                                        <span>
                                                            <svg width="35" height="15" viewBox="0 0 35 35" fill="none" xmlns="http://www.w3.org/2000/svg">
                                                                <path d="M33.2126 3.04953L33.2126 22.4767L35 22.4767L35 0.00128174L12.5233 0.00128076L12.5233 1.78628L31.9498 1.78871L-2.56206e-06 33.7356L1.26325 34.9988L33.2126 3.04953Z" fill="#464646" />
                                                            </svg>
                                                        </span>
                                                    </div>
                                                </div>

                                            </div>
                                        </a>

                                    )
                                })}
                            </div>
                        </div>

                    </div>
                </div>
            </main>

        </>
    )
}

export default Books

const wallet = [
    {
        name: "Zero to One.",
        img: book1,
        description: "The great secret of our time is that there are still uncharted frontiers to explore and new ...",
        link: "https://www.amazon.com/Zero-One-Notes-Startups-Future/dp/0804139296"
    },
    {
        name: "Well-Designed.",
        img: book2,
        description: "A guide to empathizing with users in product design, including real-world examples and practical tips.",
        link: "https://www.amazon.com/gp/product/1625274793?camp=1789&creative=9325&linkCode=as2&creativeASIN=1625274793&linkId=e2233ffbd31600b878f02a43974ff6f2"
    },
    {
        name: "Designing Products People Love.",
        img: book3,
        description: "A compilation of interviews with top product designers discussing their creative process and insights on successful product design.",
        link: "https://www.amazon.com/Designing-Products-People-Love-Successful/dp/1491923679"
    },

    {
        name: "Hooked: how to build habit-forming products.",
        img: book6,
        description: "a guide to building habit-forming products. The book presents a framework for designing products that keep users coming back...",
        link: "https://www.amazon.com/Hooked-How-Build-Habit-Forming-Products/dp/1591847788"
    },
   
    {
        name: " User Friendly: How the Hidden Rules of Design Are Changing the Way We Live, Work, and Play.",
        img: book9,
        description: "An engrossing history of how the design of commercial products and technological innovations came to be singularly focused on the user experience ",
        link: "https://www.amazon.com/User-Friendly-Hidden-Design-Changing/dp/0374279756"
    },
    {
        name: "The Best Interface Is No Interface: The Simple Path to Brilliant Technology (Voices That Matter) ",
        img: book10,
        description: "In this book, innovator Golden Krishna challenges our world of nagging, screen-based bondage, and shows how we can build a technologically advanced world without digital interfaces. ",
        link: "https://www.amazon.com/Best-Interface-No-brilliant-technology/dp/0133890333"
    },
]

const philosophy = [
    {
        name: "The Wisdom of Life.",
        img: book4,
        description: "A leading German metaphysician of the 19th century, Arthur Schopenhauer (1788–1860) exerted an influence far beyond the hermetic world of philosophy",
        link: "https://www.amazon.com/Wisdom-Life-Arthur-Schopenhauer/dp/0486435504"
    },
    {
        name: "THUS SPAKE ZARATHUSTRA.",
        img: book11,
        description: " The work is regarded as a forerunner of modern existentialist thought, a book that has provoked and stimulated students of philosophy and literature for more than 100 years.",
        link: "https://www.amazon.com/Spake-Zarathustra-Dover-Thrift-Editions/dp/0486406636"
    },
    {
        name: "When Nietzsche Wept.",
        img: book5,
        description: " A historical fiction novel exploring the relationship between philosopher Friedrich Nietzsche and psychoanalyst Josef Breuer",
        link: "https://www.amazon.com/When-Nietzsche-Wept-Novel-Obsession/dp/0062009303"
    },
    {
        name: "Beyond Good and Evil.",
        img: book12,
        description: "Beyond Good and Evil: Prelude to a Philosophy of the Future is a book by philosopher Friedrich Nietzsche, first published in 1886....",
        link: "https://www.amazon.com/Beyond-Good-Evil-Friedrich-Nietzsche/dp/1503250881/ref=pd_bxgy_img_sccl_1/137-1501301-6779600?content-id=amzn1.sym.6953b182-f957-43e6-9fe3-866e180e1e05"
    },
]

const biography = [
    {
        name: "Elon Musk: Tesla, SpaceX, and the Quest for a Fantastic Future.",
        img: book7,
        description: "A biography of the billionaire entrepreneur's life, vision and achievements in revolutionizing the automotive and space industries.",
        link: "https://www.amazon.com/Elon-Musk-SpaceX-Fantastic-Future/dp/006230125X"
    },
    {
        name: "Steve Jobs.",
        img: book8,
        description: "Based on more than forty interviews with Steve Jobs conducted over two years—as well as interviews with more than 100 family members,",
        link: "https://www.amazon.com/Steve-Jobs-Walter-Isaacson/dp/1451648537"
    }
]