

import Head from "next/head"
import {useState} from "react"
import Image from 'next/image'
import Link from 'next/link';
// images Wallets
import bag from "../../img/bag.png"



const Podcast = () =>{
    const [wallets, setWallet] = useState(true);
    const [dao, setDao] = useState(false);
    const [tools, setTools] = useState(false);

    const switchWallet = () => {
        setWallet(true);
        setDao(false);
        setTools(false);
       }
       const switchDao = () => {
        setDao(true);
        setWallet(false);
        setTools(false)
       }
       const switchTools = () => {
        setTools(true)
        setDao(false);
        setWallet(false);
       }

    return (
        <>
        <Head>
            <title>Podcast </title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
      <main>
            <div className="container">
                <div className="inner_container">
                <div className="inner_nav">
                    <span>Home  > </span>
                    <span>Taste > </span>
                    <span>Podcast</span>
                </div>
                <h1>Podcast</h1>
                    <p>Here is a list of web3 tools, DAOs and Wallets.</p>
                    <div className="filtter">
                        <ul>
                            <li onClick={ () => switchWallet()} className={wallets ?  "bottom_line  ": " "}>Fashion</li>
                            <li onClick={ () => switchDao()} className={dao ?  "bottom_line  ": " "}>Productive</li>
                            <li onClick={ () => switchTools()} className={tools ?  "bottom_line " : " "}>Watches</li>
                            <div className="fil">
                                <svg width="17" height="17" viewBox="0 0 9 10" fill="none" xmlns="http://www.w3.org/2000/svg">
                                    <path d="M0.0593468 0.237069C-0.0276426 0.386095 -0.015166 0.559994 0.0717367 0.709091L0.0841265 0.721481L3.09002 4.93221V9.68947C3.09002 9.81372 3.16453 9.92549 3.26391 9.97513C3.30116 10 3.3509 10 3.40054 10C3.47506 10 3.53718 9.97513 3.5993 9.92549L5.12707 8.64612C5.20158 8.584 5.23884 8.4971 5.23884 8.4101V4.93221L8.24473 0.721474L8.25712 0.709084C8.34411 0.560059 8.35649 0.38616 8.26951 0.237063C8.18252 0.0880369 8.03348 0.0010409 7.85961 0.0010409H0.456895C0.295395 -0.0113489 0.133903 0.0880303 0.059377 0.237063L0.0593468 0.237069Z" fill="#383838"/>
                                </svg>
                            </div>
                        </ul>
                    </div>
                    <div className="inner_blockes">
          {wallet.map(item => {
              return (
                  <a  key={item} href={item.link} target="_blink">
                      <div key={item.name} className="block_books">
                      <div className="block_book_f">
                        <div className="block_books_img">
                        <Image
                            src={item.img}
                            alt="Picture of the author"
                            objectFit='cover'
                            // layout='fill'
                            objectPosition="center"
                            placeholder="blur"
                            quality={100}
                            />
                        </div>
                       <div className="data_des">
                       <h2>The best</h2>
                        <p>From essays to videos and tweets, this page is a collection of learning materials that I enjoy. I add to the list frequently, </p>
                        <span>
                            <svg width="25" height="25" viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg">
                            <path d="M9.10675 7.13995C9.3289 7.3621 9.3215 7.71279 9.08751 7.91649L6.75277 9.95844C6.51879 10.1621 6.14788 10.1493 5.92573 9.92717C5.70358 9.70502 5.69077 9.33412 5.89447 9.10013L7.93641 6.7654C8.14011 6.53141 8.4908 6.52401 8.71295 6.74616L9.10675 7.13995Z" fill="white"/>
                            <path d="M6.91471 6.16017C6.69638 5.94183 6.76614 5.7629 7.08412 5.76253L9.52835 5.75962C9.83634 5.75925 10.0894 6.01234 10.0891 6.32034L10.0862 8.7745C10.0858 9.0825 9.90685 9.16225 9.68851 8.94391L6.90968 6.16508L6.91471 6.16017Z" fill="white"/>
                            <circle cx="8" cy="8" r="7.5" stroke="white"/>
                            </svg>
                        </span>
                       </div>
                      </div>
                  
                  </div>
                  </a>
              )
          })}
          </div>
          <div className="inner_container inner_teste">
          <h2>More</h2>
                <div className="grid-teste grid">
                <Link href="/taste/web3stack">
                    <div className="teste_box">
                 
                      <div className="inner_taste_box">
                      <svg  viewBox="0 0 17 17" fill="none" xmlns="http://www.w3.org/2000/svg">
                        <path d="M0.846149 4.40155L8.32757 8.46715C8.39243 8.50175 8.4648 8.51984 8.53831 8.51984C8.61182 8.51984 8.6842 8.50175 8.74905 8.46715L16.2305 4.40155C16.2987 4.36784 16.3555 4.31472 16.3937 4.24885C16.4319 4.18298 16.4497 4.1073 16.445 4.03132C16.4403 3.95533 16.4133 3.88243 16.3673 3.82175C16.3213 3.76108 16.2585 3.71534 16.1866 3.69029L8.70515 0.634497C8.59826 0.590584 8.47836 0.590584 8.37147 0.634497L0.890054 3.69029C0.818167 3.71534 0.755284 3.76108 0.709301 3.82175C0.663318 3.88243 0.636284 3.95533 0.631594 4.03132C0.626903 4.1073 0.644765 4.18298 0.682937 4.24885C0.721109 4.31472 0.777889 4.36784 0.846149 4.40155Z" fill="white"/>
                        <path d="M16.1842 7.35972L14.5773 6.6748L8.74669 9.84475C8.68183 9.87934 8.60945 9.89743 8.53595 9.89743C8.46244 9.89743 8.39006 9.87934 8.3252 9.84475L2.49461 6.6748L0.887691 7.35972C0.819637 7.39545 0.762647 7.4491 0.722887 7.51488C0.683126 7.58066 0.662109 7.65605 0.662109 7.73292C0.662109 7.80978 0.683126 7.88517 0.722887 7.95095C0.762647 8.01673 0.819637 8.07038 0.887691 8.10611L8.36911 12.4088C8.43255 12.4476 8.50548 12.4681 8.57985 12.4681C8.65422 12.4681 8.72715 12.4476 8.7906 12.4088L16.272 8.10611C16.3368 8.063 16.3884 8.00279 16.421 7.93217C16.4537 7.86154 16.4662 7.78326 16.4571 7.70598C16.448 7.6287 16.4177 7.55544 16.3695 7.49433C16.3214 7.43321 16.2572 7.38662 16.1842 7.35972Z" fill="white"/>
                        <path d="M16.185 11.2592L14.8151 10.6621L8.74746 13.9638C8.6826 13.9984 8.61022 14.0165 8.53672 14.0165C8.46321 14.0165 8.39083 13.9984 8.32597 13.9638L2.2583 10.6621L0.888459 11.2592C0.818476 11.2955 0.759807 11.3503 0.718857 11.4177C0.677907 11.485 0.65625 11.5624 0.65625 11.6412C0.65625 11.72 0.677907 11.7973 0.718857 11.8647C0.759807 11.9321 0.818476 11.9869 0.888459 12.0232L8.36988 16.4137C8.43474 16.4483 8.50711 16.4664 8.58062 16.4664C8.65413 16.4664 8.7265 16.4483 8.79136 16.4137L16.2728 12.0232C16.3395 11.9795 16.3928 11.9181 16.4266 11.8458C16.4605 11.7736 16.4736 11.6934 16.4645 11.6141C16.4554 11.5349 16.4244 11.4597 16.375 11.397C16.3257 11.3344 16.2599 11.2867 16.185 11.2592Z" fill="white"/>
                      </svg>
                         <h2>Stack</h2>
                         <p>From essays to videos and tweets, this page is a collection of learning materials that.</p>
                         <button>
                            <p>Enter</p>
                            <span>
                            <svg width="25" height="25" viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg">
                                <path d="M9.10675 7.13995C9.3289 7.3621 9.3215 7.71279 9.08751 7.91649L6.75277 9.95844C6.51879 10.1621 6.14788 10.1493 5.92573 9.92717C5.70358 9.70502 5.69077 9.33412 5.89447 9.10013L7.93641 6.7654C8.14011 6.53141 8.4908 6.52401 8.71295 6.74616L9.10675 7.13995Z" fill="black"/>
                                <path d="M6.91471 6.16017C6.69638 5.94183 6.76614 5.7629 7.08412 5.76253L9.52835 5.75962C9.83634 5.75925 10.0894 6.01234 10.0891 6.32034L10.0862 8.7745C10.0858 9.0825 9.90685 9.16225 9.68851 8.94391L6.90968 6.16508L6.91471 6.16017Z" fill="black"/>
                                <circle cx="8" cy="8" r="7.5" stroke="black"/>
                                </svg>
                            </span>
                         </button>
                      </div>
                    
                    </div>
                    </Link>
                    <Link href="/taste/aesthetic">
                    <div className="teste_box">
                        <div className="inner_taste_box">
                        <svg  style={{width:"40px"}}viewBox="0 0 402 611" fill="none" xmlns="http://www.w3.org/2000/svg">
                            <path d="M200.767 505.867C258.22 505.867 313.183 480.976 351.34 437.627C383.695 400.913 401.533 353.835 401.533 305.096C401.533 256.357 383.695 209.481 351.34 172.565C313.179 129.216 258.215 104.325 200.767 104.325C143.319 104.325 88.3507 129.216 50.1933 172.565C17.8387 209.273 0 256.357 0 305.096C0 353.835 17.8387 400.919 50.1933 437.627C88.3547 480.976 143.319 505.867 200.767 505.867ZM193.095 148.707C193.095 144.352 196.621 140.826 200.975 140.826C205.329 140.826 208.855 144.352 208.855 148.707V297.427H279.377C283.731 297.427 287.257 300.953 287.257 305.307C287.257 309.661 283.731 313.187 279.377 313.187H200.767C196.413 313.187 192.887 309.661 192.887 305.307V148.707L193.095 148.707Z" fill="white"/>
                            <path d="M345.954 144.973L333.303 60.1453C328.116 25.9213 298.251 0 263.615 0H137.719C103.083 0 73.2139 25.9267 68.0312 60.1453L55.5781 144.973C95.1928 108.885 147.047 88.7653 200.765 88.7653C254.691 88.7653 306.338 109.093 345.951 144.973H345.954Z" fill="white"/>
                            <path d="M55.5801 465.213L68.2311 550.041C73.4186 584.265 103.283 610.187 137.919 610.187H263.815C298.451 610.187 328.32 584.26 333.503 550.041L345.956 465.213C306.342 501.301 254.487 521.421 200.77 521.421C146.843 521.421 95.1962 501.093 55.5829 465.213H55.5801Z" fill="white"/>
                            </svg>
                        <h2>Aesthetic</h2>
                   
                         <p>From essays to videos and tweets, this page is a collection of learning materials that.</p>
                         <button>
                            <p>Enter</p>
                            <span>
                            <svg width="25" height="25" viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg">
                                <path d="M9.10675 7.13995C9.3289 7.3621 9.3215 7.71279 9.08751 7.91649L6.75277 9.95844C6.51879 10.1621 6.14788 10.1493 5.92573 9.92717C5.70358 9.70502 5.69077 9.33412 5.89447 9.10013L7.93641 6.7654C8.14011 6.53141 8.4908 6.52401 8.71295 6.74616L9.10675 7.13995Z" fill="black"/>
                                <path d="M6.91471 6.16017C6.69638 5.94183 6.76614 5.7629 7.08412 5.76253L9.52835 5.75962C9.83634 5.75925 10.0894 6.01234 10.0891 6.32034L10.0862 8.7745C10.0858 9.0825 9.90685 9.16225 9.68851 8.94391L6.90968 6.16508L6.91471 6.16017Z" fill="black"/>
                                <circle cx="8" cy="8" r="7.5" stroke="black"/>
                                </svg>
                            </span>
                         </button>
                        </div>
                    
                    </div>
                    </Link>
                    <Link href="/taste/books">
                        <div className="teste_box">
                        <div className="inner_taste_box">
                            <svg  version="1.1" fill="#fff" viewBox="0 0 700 700" xmlns="http://www.w3.org/2000/svg">
                            <path d="m602.61 328.55v66.418l-286.49 165.03-251.72-162.8c-49.215-31.832-62.906-95.777-12.223-124.98l51.43-29.625c-12.75-29.633-6.6875-62.562 25.762-81.258l280.07-161.33 270.38 172.47v111.61l-77.191 44.469zm-285.23 162.73-251.45-162.03c-28.297-18.238-23.609 22.883 4.2734 40.664l247 157.56 259.17-148.44v-35.371l-259 147.62zm77.809-136.82 258.38-141.25v54.941l-259.17 148.44-247.01-157.56c-27.879-17.785-26.141-80.469 2.7461-63.125l245.05 158.56z" fill-rule="evenodd"/>
                            </svg>
                        <h2>Books</h2>
                    
                         <p>From essays to videos and tweets, this page is a collection of learning materials that.</p>
                         <button>
                            <p>Enter</p>
                            <span>
                            <svg width="25" height="25" viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg">
                                <path d="M9.10675 7.13995C9.3289 7.3621 9.3215 7.71279 9.08751 7.91649L6.75277 9.95844C6.51879 10.1621 6.14788 10.1493 5.92573 9.92717C5.70358 9.70502 5.69077 9.33412 5.89447 9.10013L7.93641 6.7654C8.14011 6.53141 8.4908 6.52401 8.71295 6.74616L9.10675 7.13995Z" fill="black"/>
                                <path d="M6.91471 6.16017C6.69638 5.94183 6.76614 5.7629 7.08412 5.76253L9.52835 5.75962C9.83634 5.75925 10.0894 6.01234 10.0891 6.32034L10.0862 8.7745C10.0858 9.0825 9.90685 9.16225 9.68851 8.94391L6.90968 6.16508L6.91471 6.16017Z" fill="black"/>
                                <circle cx="8" cy="8" r="7.5" stroke="black"/>
                                </svg>
                            </span>
                         </button>
                        </div>
                        </div>
                    </Link>
                   
                </div>
            </div>
                </div>
            </div>
      </main>
        
        </>
    )
}

export default Podcast

const wallet = [
    {
        name:"Rainbow",
        img:bag,
        description:"The fun, simple, & secure way to explore Web3, NFTs, & Ethereum.",
        link:"https://rainbow.me/"
    },
    {
        name:"Coinbase",
        img:bag,
        description:"Self-custody, mobile crypto wallet and Web3 dapp browser.",
        link:"https://www.coinbase.com/wallet"
    },
    {
        name:"Metamask",
        img:bag,
        description:"A crypto wallet & gateway to blockchain apps.",
        link:"https://metamask.io/"
    },
    {
        name:"Ledger",
        img:bag,
        description:"The smartest way to secure, buy and exchange crypto.",
        link:"https://www.ledger.com/"
    },
    {
        name:"Trustwallet",
        img:bag,
        description:"Buy, store, collect NFTs, exchange & earn crypto.",
        link:"https://trustwallet.com/"
    },
    {
        name:"Gnosis Safe",
        img:bag,
        description:"The most trusted platform to manage digital assets.",
        link:"https://gnosis-safe.io/"
    }
]