

import Head from "next/head"
import { useState } from "react"
import Image from 'next/image'
import Link from 'next/link';
// images Wallets
import book1 from "../../img/flagretn.png"
import book2 from "../../img/9af79fd06e34dea3cd27c4e1cd6ec7343ce20af4.jpeg"
import book3 from "../../img/ab6765630000ba8adb54ab35c7089680aa6c4739.jpeg"
import book4 from "../../img/ab6765630000ba8a563ebb538d297875b10114b7.jpeg"
import book5 from "../../img/avatars-000077558236-x3rljg-original.jpg"
import book6 from "../../img/Copy_of_All-In_Logos_3_600x.webp"
import book7 from "../../img/313x0w.webp"
import book8 from "../../img/41-z0MNHwKL._SX326_BO1,204,203,200_.jpg"

const Podcast = () => {
    const [wallets, setWallet] = useState(true);
    const [dao, setDao] = useState(false);
    const [tools, setTools] = useState(false);

    const switchWallet = () => {
        setWallet(true);
        setDao(false);
        setTools(false);
    }
    const switchDao = () => {
        setDao(true);
        setWallet(false);
        setTools(false)
    }
    const switchTools = () => {
        setTools(true)
        setDao(false);
        setWallet(false);
    }

    return (
        <>
            <Head>
                <title>Podcast </title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
                <div className="container container_podcast">
                    <div className="inner_container">
                        <div className="inner_nav">
                            <span><Link href="/">Home</Link> &gt; </span>
                            <span><Link href="/oasis">Oasis</Link> &gt; </span>
                            <span><Link href="/taste/books">Podcast</Link> </span>
                        </div>
                        <h1>Podcast</h1>
                        <p> From thought-provoking interviews to fascinating stories and everything in between, Check out my top podcast recommendations.</p>
                        <div className="filtter">
                            <ul>
                                <li onClick={() => switchWallet()} className={wallets ? "bottom_line  " : " "}>All</li>

                                <div className="fil">
                                    <svg width="17" height="17" viewBox="0 0 9 10" fill="none" xmlns="http://www.w3.org/2000/svg">
                                        <path d="M0.0593468 0.237069C-0.0276426 0.386095 -0.015166 0.559994 0.0717367 0.709091L0.0841265 0.721481L3.09002 4.93221V9.68947C3.09002 9.81372 3.16453 9.92549 3.26391 9.97513C3.30116 10 3.3509 10 3.40054 10C3.47506 10 3.53718 9.97513 3.5993 9.92549L5.12707 8.64612C5.20158 8.584 5.23884 8.4971 5.23884 8.4101V4.93221L8.24473 0.721474L8.25712 0.709084C8.34411 0.560059 8.35649 0.38616 8.26951 0.237063C8.18252 0.0880369 8.03348 0.0010409 7.85961 0.0010409H0.456895C0.295395 -0.0113489 0.133903 0.0880303 0.059377 0.237063L0.0593468 0.237069Z" fill="#383838" />
                                    </svg>
                                </div>
                            </ul>
                        </div>
                        <div className="inner_blockes">
                            <div className={wallets ? "trans statesOn" : "trans statesOff "}>
                                {wallet.map(item => {
                                    return (
                                        <a key={item} href={item.link} target="_blink">
                                            <div key={item.name} className="block_books">
                                                <div className="block_book_f">
                                                    <div className="block_books_img">
                                                        <Image
                                                            src={item.img}
                                                            alt="Picture of the author"
                                                            objectFit='cover'
                                                            layout='fill'
                                                            objectPosition="center"
                                                            placeholder="blur"
                                                            quality={100}
                                                        />
                                                    </div>
                                                    <div className="data_des">
                                                        <h2>{item.name}</h2>
                                                        <p>{item.description} </p>
                                                        
                                                           
                                                           
                                                        <span>
                                                            <svg width="35" height="15" viewBox="0 0 35 35" fill="none" xmlns="http://www.w3.org/2000/svg">
                                                                <path d="M33.2126 3.04953L33.2126 22.4767L35 22.4767L35 0.00128174L12.5233 0.00128076L12.5233 1.78628L31.9498 1.78871L-2.56206e-06 33.7356L1.26325 34.9988L33.2126 3.04953Z" fill="#464646" />
                                                            </svg>
                                                        </span>
                                                    </div>
                                                </div>

                                            </div>
                                        </a>

                                    )
                                })}
                            </div>


                        </div>

                    </div>
                </div>
            </main>

        </>
    )
}

export default Podcast

const wallet = [
    {
        name: "FLAGRANT",
        img: book1,
        description: "Flagrant is a comedy podcast that delivers unfiltered, unapologetic, and unruly hot takes directly to your dome piece.....",
        link: "https://www.youtube.com/@OfficialFlagrant"
    },
    {
        name: "The All-In Podcast",
        img: book6,
        description: "Chamath Palihapitiya, Jason Calacanis, David Sacks & David Friedberg cover all things economic, tech, political, social & poker.",
        link: "https://www.youtube.com/@allin/featured"
    },
    {
        name: "Brilliant Idiots",
        img: book5,
        description: "Charlamagne Tha God and Andrew Schulz are The Brilliant Idiots. Join them each week as they explore the issues of the day in a style that's often idiotic...",
        link: "https://www.youtube.com/@BrilliantIdiotsPod"
    },
    {
        name: "UI Breakfast: UI/UX Design and Product Strategy",
        img: book7,
        description: "Exciting conversations about UI/UX design, SaaS products, marketing, and so much more..",
        link: "https://podcasts.apple.com/us/podcast/ui-breakfast-ui-ux-design-and-product-strategy/id939175693"
    },


    {
        name: "The Joe Rogan Experience",
        img: book2,
        description: "Is a long form conversation hosted by comedian Joe Rogan with friends and guests that have included comedians, actors, musicians, MMA fighters, authors...",
        link: "https://open.spotify.com/show/4rOoJ6Egrf8K2IrywzwOMk"
    },
    {
        name: "Huberman Lab",
        img: book3,
        description: "Dr. Andrew Huberman is a professor of neurobiology and ophthalmology at Stanford School of Medicine and host of the Huberman Lab podcast..",
        link: "https://www.youtube.com/@hubermanlab"
    },
    {
        name: "Lex Fridman",
        img: book4,
        description: "Lex Fridman Podcast. Conversations about the nature of intelligence, consciousness, love, and power",
        link: "https://www.youtube.com/@lexfridman"
    }

]

