import Head from 'next/head'
import Image from 'next/image'
import Script from 'next/script'
import {useState} from "react"
import Link from 'next/link';
// images Wallets
import Rainbow from "../../img/wallets/rain.png"
import Coinbase from "../../img/wallets/Coinbase.png"
import Metamask from "../../img/wallets/Metamask.png"
import Ledger from "../../img/wallets/Ledger.png"
import Trustwallet from "../../img/wallets/Trustwallet.png"
import Gnosis_Safe from "../../img/wallets/Gnosis Safe.png"
// images Daos
import DeveloperDao from "../../img/daos/Elliffpse 4.png"
import VectorDAO from "../../img/daos/Ellipse 4.png"
import Fwb from "../../img/daos/Elliphgse 4.png"
import Citydao from "../../img/daos/Ellinhgge 4.png"
import Forefront from "../../img/daos/Elligbfgbfgpse 4.png"
import Syndicate from "../../img/daos/Ellipse fgsdgs4.png"

// images tools
import ValueApp from "../../img/tools/value.jpeg"
import Raritysniper from "../../img/tools/favicon.png"
import Snapshot from "../../img/tools/Group 122.png"
import Guild from "../../img/tools/L8tmHbzm_400x400.jpg"
// image tool daily

import figma from "../../img/dailyUse/figma.svg"
import vscode from "../../img/dailyUse/vscode.svg"
import appleMuisc from "../../img/dailyUse/appleMuisc.svg"
import obsidian from "../../img/dailyUse/obsidian.svg"
import linear from "../../img/dailyUse/linear.svg"
import arc from "../../img/dailyUse/arc.svg"
import spoitfy from "../../img/dailyUse/spoitfy.svg"

export default function Stack() {
//    const [all, setAll] = useState(true);

   const [table1 , setTable1] = useState(true);
   const [table2 , setTable2] = useState(false);
   const [table3 , setTable3] = useState(false);


   const switch1 = () => {
    setTable1(true);
    setTable2(false);
    setTable3(false);
 
   }
   const switch2 = () => {
    setTable1(false);
    setTable2(true);
    setTable3(false);
    
   }
   const switch3 = () => {
    setTable1(false);
    setTable2(false);
    setTable3(true);
 
   }
   const switch4 = () => {
    setTable1(false);
    setTable2(false);
    setTable3(false);
   
   }
   const switch5 = () => {
    setTable1(false);
    setTable2(false);
    setTable3(false);
   
   }
    
  

  return (
    <>
      <Head>
        <title>Stack</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
   
       <div className="container">
        <div className="inner_container">
        <div className="inner_nav">
          <span><Link href="/">Home</Link>   &gt; </span>
          <span><Link href="/oasis">Oasis</Link>  &gt; </span>
          <span><Link href="/taste/web3stack">Stack</Link></span>
            
        </div>
          <h1>Stack</h1>
          <p>Explore my essential digital tools - apps, software, and online services I use every day to stay organized, productive, and efficient.</p>
         
          <div className="filtter">
            <ul>
                <li onClick={ () => switch1()} className={table1 ?  "bottom_line  ": " "}>Daily Usage</li>
                <li onClick={ () => switch2()} className={table2 ?  "bottom_line  ": " "}>Wallets</li>
                <li onClick={ () => switch3()} className={table3 ?  "bottom_line  ": " "}>Daos</li>
               
                <div className="fil">
                <svg width="17" height="17" viewBox="0 0 9 10" fill="none" xmlns="http://www.w3.org/2000/svg">
                    <path d="M0.0593468 0.237069C-0.0276426 0.386095 -0.015166 0.559994 0.0717367 0.709091L0.0841265 0.721481L3.09002 4.93221V9.68947C3.09002 9.81372 3.16453 9.92549 3.26391 9.97513C3.30116 10 3.3509 10 3.40054 10C3.47506 10 3.53718 9.97513 3.5993 9.92549L5.12707 8.64612C5.20158 8.584 5.23884 8.4971 5.23884 8.4101V4.93221L8.24473 0.721474L8.25712 0.709084C8.34411 0.560059 8.35649 0.38616 8.26951 0.237063C8.18252 0.0880369 8.03348 0.0010409 7.85961 0.0010409H0.456895C0.295395 -0.0113489 0.133903 0.0880303 0.059377 0.237063L0.0593468 0.237069Z" fill="#383838"/>
                </svg>
            </div>
            </ul>
            
        </div>
        <div className={table1 ?  "trans statesOn" : "trans statesOff "}>
          <div className="inner_stack">
           
          {Tools.map(item => {
              return (
                  <a  key={item} href={item.link} target="_blink">
                      <div key={item.name} className="block">
                      <div className="top_block">
                        <div className="logo_stack logo_stack_icon">
                        <Image
                        className='logo_stack_icon_inner'
                            src={item.img}
                            alt="Picture of the author"
                            objectFit='cover'
                            layout='fill'
                            objectPosition="center"
                          
                          
                            />
                        </div>
                        <div className='arrow'> 
                                <svg width="35" height="35" viewBox="0 0 35 35" fill="none" xmlns="http://www.w3.org/2000/svg">
                                <path d="M33.2126 3.04953L33.2126 22.4767L35 22.4767L35 0.00128174L12.5233 0.00128076L12.5233 1.78628L31.9498 1.78871L-2.56206e-06 33.7356L1.26325 34.9988L33.2126 3.04953Z" fill="#464646"/>
                                </svg>
                        </div>
                      </div>
                      <h1>{item.name}</h1>
                      <p>{item.description}</p>
                   
                  </div>
                  </a>
              )
          })}
          </div>
          </div>
          <div className={table2 ?  "trans statesOn" : "trans statesOff "}>
          <div className="inner_stack">
           
          {wallet.map(item => {
              return (
                  <a  key={item} href={item.link} target="_blink">
                      <div key={item.name} className="block">
                      <div className="top_block">
                        <div className="logo_stack">
                        <Image
                            src={item.img}
                            alt="Picture of the author"
                            objectFit='cover'
                            layout='fill'
                            objectPosition="center"
                            placeholder="blur"
                            quality={100}
                            />
                        </div>
                        <div className='arrow'> 
                                <svg width="35" height="35" viewBox="0 0 35 35" fill="none" xmlns="http://www.w3.org/2000/svg">
                                <path d="M33.2126 3.04953L33.2126 22.4767L35 22.4767L35 0.00128174L12.5233 0.00128076L12.5233 1.78628L31.9498 1.78871L-2.56206e-06 33.7356L1.26325 34.9988L33.2126 3.04953Z" fill="#464646"/>
                                </svg>
                        </div>
                      </div>
                      <h1>{item.name}</h1>
                      <p>{item.description}</p>
                     
                  </div>
                  </a>
              )
          })}
          </div>
          </div>
          <div className={table3 ?  "statesOn" : "statesOff "}>
    
          <div className="inner_stack">
          {Daos.map(item => {
              return (
                  <a  key={item} href={item.link} target="_blink">
                  <div className="block">
                       <div className="top_block">
                        <div className="logo_stack">
                        <Image
                            src={item.img}
                            alt="Picture of the author"
                            objectFit='cover'
                            layout='fill'
                            objectPosition="center"
                            placeholder="blur"
                            quality={100}
                            />
                        </div>
                        <div className='arrow'> 
                                <svg width="35" height="35" viewBox="0 0 35 35" fill="none" xmlns="http://www.w3.org/2000/svg">
                                <path d="M33.2126 3.04953L33.2126 22.4767L35 22.4767L35 0.00128174L12.5233 0.00128076L12.5233 1.78628L31.9498 1.78871L-2.56206e-06 33.7356L1.26325 34.9988L33.2126 3.04953Z" fill="#464646"/>
                                </svg>
                        </div>
                      </div>
                      <h1>{item.name}</h1>
                      <p>{item.description}</p>
                  </div>
                  </a>
              )
          })}
          </div>
          </div>
         
          <div className="container">
        
            </div>
        </div>
       </div>
       <Script
        src="https://www.googletagmanager.com/gtag/js?id=G-H699TZ29QW"
        strategy="afterInteractive"
      />
      <Script id="google-analytics" strategy="afterInteractive">
        {`
         window.dataLayer = window.dataLayer || [];
         function gtag(){dataLayer.push(arguments);}
         gtag('js', new Date());
 
         gtag('config', 'G-H699TZ29QW');
        `}
      </Script>
      </main>
  
</>
  )
}

const wallet = [
    {
        name:"Rainbow",
        img:Rainbow,
        description:"The fun, simple, & secure way to explore Web3, NFTs, & Ethereum.",
        link:"https://rainbow.me/"
    },
    {
        name:"Coinbase",
        img:Coinbase,
        description:"Self-custody, mobile crypto wallet and Web3 dapp browser.",
        link:"https://www.coinbase.com/wallet"
    },
    {
        name:"Metamask",
        img:Metamask,
        description:"A crypto wallet & gateway to blockchain apps.",
        link:"https://metamask.io/"
    },
    {
        name:"Ledger",
        img:Ledger,
        description:"The smartest way to secure, buy and exchange crypto.",
        link:"https://www.ledger.com/"
    },
    {
        name:"Trustwallet",
        img:Trustwallet,
        description:"Buy, store, collect NFTs, exchange & earn crypto.",
        link:"https://trustwallet.com/"
    },
    {
        name:"Gnosis Safe",
        img:Gnosis_Safe,
        description:"The most trusted platform to manage digital assets.",
        link:"https://gnosis-safe.io/"
    }
]

const Daos = [
    {
        name:"DeveloperDao",
        img:DeveloperDao,
        description:"Accelerate the education of a new wave of web3 builders.",
        link:"https://www.developerdao.com/"
    },
    {
        name:"VectorDAO",
        img:VectorDAO,
        description:"A collective of designers making Internet money easier to use.",
        link:"https://vectordao.com/"
    },
    {
        name:"FRIENDS with BENEFITS",
        img:Fwb,
        description:"A digital cornerstone between technology and culture.",
        link:"https://www.fwb.help/"
    },
    {
        name:"Citydao",
        img:Citydao,
        description:"Experiment in decentralized land ownership.",
        link:"https://citydao.io/"
    },
    {
        name:"Forefront",
        img:Forefront,
        description:"The port of entry to social clubs and digital cities.",
        link:"https://rainbow.me/"
    },
    {
        name:"Syndicate",
        img:Syndicate,
        description:"Decentralized investing protocol + social network.",
        link:"https://syndicate.io/"
    }
]


const Tools = [
    {
        name:"Figma",
        img:figma,
        description:"Figma is a web-based design tool with real-time collaboration used for UI and UX design.",
        link:"https://www.figma.com/"
    },
    {
        name:"VS code",
        img:vscode,
        description:"Free, open-source code editor for debugging, code refactoring, and multi-language support.",
        link:"https://code.visualstudio.com/"
    },
    {
        name:"Apple Music",
        img:appleMuisc,
        description:"Sub-based music streaming service with a vast library, personalized recommendations, and offline downloads.",
        link:"https://music.apple.com"
    },
    {
        name:"Arc",
        img:arc,
        description:"Fast and secure web browser with built-in privacy features and ad-blocker.",
        link:"https://arc.net/"
    },
    {
        name:"Obsidian",
        img:obsidian,
        description:"Note-taking app with a customizable and interconnected graph view for easy navigation and organization.",
        link:"https://obsidian.md/"
    },
    {
        name:"Linear",
        img:linear,
        description:"Project management tool for agile teams with issue tracking, sprint planning, and analytics.",
        link:"https://linear.app/"
    },
    {
        name:"Spoitfy",
        img:spoitfy,
        description:"Music streaming service with a vast library, personalized recommendations, and social sharing features.",
        link:"https://open.spotify.com/"
    },
   
]