import Head from 'next/head'
import Image from 'next/image'
import Footer from "../../components/footer"
import BlogNav from "../../components/BlogNav"
import img6 from "../../img/blog/3.png"
 const Blog1  = () => {
    return    (
        <>
        <Head>
            <title>Projects | Mohamed Sadiq</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <div className="container">
          <div className="inner_container">
          <BlogNav />
          <div className="blog_photo inner_blog">
                <Image
                    src={img6}
                    alt="Picture of the author"
                    objectFit='cover'
                    layout='fill'
                    objectPosition="center"
                    placeholder="blur"
                    quality={100}
                />
            </div>
            <div className="content_blog">
            <h1>Game and please</h1>
            <span>January, 12, 2021</span>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque molestie, est et malesuada tristique, nunc justo congue urna, non laoreet arcu justo a nibh. Phasellus tempus tempus ipsum vitae vehicula. Ut pharetra, nibh sit amet vulputate dignissim, quam justo dapibus massa, nec aliquam nunc urna nec lacus. Vivamus fermentum dolor at urna porttitor ullamcorper. Nullam mattis dui neque, sed tempor nisi pellentesque ac. Integer pellentesque consectetur ipsum quis porttitor. Duis accumsan tristique mauris, id tincidunt felis vulputate ut. Quisque sit amet rhoncus augue. In suscipit justo eget sem volutpat blandit. Quisque dignissim dui risus, sed consectetur nisl tempor at. Mauris id elit ac orci hendrerit lobortis eget quis nunc. Mauris urna ex, venenatis eu purus aliquet, interdum tincidunt urna. Cras vel hendrerit lectus, at suscipit turpis.
            Nullam vitae euismod libero, pulvinar blandit justo. Donec nec ante arcu. Nullam congue metus sed turpis malesuada, sed malesuada purus pretium. Sed ligula mi, molestie vel erat sed, faucibus pharetra lorem. In tortor metus, convallis ut quam in, eleifend interdum nulla. Cras vestibulum ac nunc eget consequat. Cras in tellus dolor. Etiam varius risus mattis lorem dignissim, ut auctor neque aliquet. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.
            Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Quisque quis erat at turpis dignissim euismod nec vel mi. Suspendisse ut odio ornare sem egestas fermentum. Praesent pulvinar fermentum ipsum quis faucibus. Quisque a odio id neque ultricies pulvinar. In at sem sapien. Vivamus ac fringilla lacus, in tempor felis. Vestibulum non laoreet diam, sit amet sollicitudin erat. Aliquam hendrerit neque a cursus elementum. Duis non consectetur ante. Pellentesque ac urna et odio cursus lobortis. Phasellus scelerisque eu velit a pharetra.
            Donec placerat lectus sed venenatis accumsan. Sed urna magna, varius pellentesque dignissim a, consectetur nec dui. Curabitur ac ex nisl. Phasellus iaculis dui at metus tempus iaculis. Pellentesque metus erat, gravida nec porta at, imperdiet et eros. Ut tempus vel mauris ac bibendum. Sed viverra elit dictum, tempor sem sit amet, pretium est. Curabitur rhoncus molestie maximus. Donec fermentum tincidunt diam eu vestibulum. Ut venenatis gravida nisl, in tincidunt ex pellentesque vel. Praesent nec neque in nulla dignissim suscipit.
            Integer ultrices mi vitae mauris vulputate condimentum eget in nunc. Integer id nisi et eros efficitur posuere id vel tellus. Aliquam elit sem, tristique eu finibus quis, semper id mi. Praesent tempor condimentum maximus. Fusce placerat rutrum rutrum. Praesent porttitor nisi et risus hendrerit condimentum. Vivamus nibh sapien, porttitor at pharetra quis, malesuada et nisl. Mauris at dictum tellus. Pellentesque eget urna et turpis molestie condimentum.</p>
          </div>
            </div>
        </div>
        <Footer />
        </>
    )
}

export default Blog1

