import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link';
import Script from 'next/script'
import useSound from 'use-sound';
// images
import me from "../img/me.png"
import setup from "../img/setup.png"

export default function About() {
  // Sound hook
  const [play] = useSound("/sound.mp3");

  return (
    <>
      <Head>
        <title>About Me</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>

        <div className="container">
          <div className="inner_container about_me">
            <h1>Product designer building internet software.</h1>
            <p>Since 2017, I have been working as a product designer with expertise in designing and building digital products, including websites, mobile apps, and internet software. My focus is on creating user-centered designs that solve business problems while providing a seamless user experience. Additionally, I'm passionate about the possibilities presented by the emerging field of Web3 and how it can provide more autonomy and security to users.</p>
            <a
                className="links"
                href="/cv.pdf"
                alt="alt text"
                target="_blank"
                rel="noopener noreferrer"
            >Resume</a>
            <div className="image_conta">
            <div className="about_me_images about1">
              <Image
                src={setup}
                alt="Picture of the author"
                quality={100}
                placeholder="blur"
              />
              <h5>My Setup</h5>
              <p>This photo showcases my setup - a snapshot of the tools and personal items that make up my workspace for work or relaxation.</p>
              </div>
              <div className="about_me_images about2">
               <Image
                src={me}
                alt="Picture of the author"
                quality={100}
                placeholder="blur"
              />
               <h5>Just Me</h5>
              <p>A self-portrait photograph of me</p>
            </div>
            </div>
          </div>
        </div>
        <Script
          src="https://www.googletagmanager.com/gtag/js?id=G-H699TZ29QW"
          strategy="afterInteractive"
        />
        <Script id="google-analytics" strategy="afterInteractive">
          {`
         window.dataLayer = window.dataLayer || [];
         function gtag(){dataLayer.push(arguments);}
         gtag('js', new Date());
 
         gtag('config', 'G-H699TZ29QW');
        `}
        </Script>
      </main>

    </>
  )
}


