import Head from 'next/head'
import Image from 'next/image'
import BlogContent from "../components/blogContent"
const Blogs = () => {
    return (
       <>
            <Head>
            <title>Blog</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
            </Head>
        <main>
            <div className="container">
            <div className="inner_container">
                <h1>Blog</h1>
                <p>Step into my virtual world, where I share my insights on a range of topics, from science to self-improvement. </p>
                <BlogContent link1={"blog/blog1"} link2={"blog/blog2"} link3={"blog/blog3"}/>
             
            </div>
            </div>
        </main>
        </>
     
    )
}
export default Blogs