import Head from 'next/head'
import Image from 'next/image'
import BlogContent from "../components/blogContent"
const Blogs = () => {
    return (
       <>
            <Head>
            <title>Blogs | Mohamed Sadiq</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
            </Head>
        <main>
            <div className="container">
            <div className="inner_container">
                <h1>Blog</h1>
                <p>Here where I write what I find interesting and useful.</p>
                <BlogContent />
            </div>
            </div>
        </main>
        </>
     
    )
}
export default Blogs