import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link';
import useSound from 'use-sound';
// images
import developerDao from "../img/ezgif.com-gif-maker.gif"
import developerDaoFm from "../img/developerdaofm.png"
import nftweb3 from "../img/nftweb3.png"
import web3cons from "../img/loginweb3.png"
import watchcrypto from "../img/watchcrypto.png"
import applewatch from "../img/applewatch.png"
import westworldwatch from "../img/d218e12214cee039f32a61690163c91d.jpg"
import weatherapp from "../img/weatherapp.png"
import vscode from "../img/vscode.png"
import cryptocon from "../img/cdcs.png"
import libyatells from "../img/libyatells.png"
import trustWallet from "../img/trustwallet.jpg"
import lastwebsite from "../img/lastwebsite.jpg"
import ovo from "../img/ovo.png"
import folim from "../img/folim.png"
import gm from "../img/gm.png"
import nasir from "../img/bitcoin.png"
import car from "../img/car.png"
import csc from "../img/fdsvedf.png"
import delta from "../img/delta.png"
import indoor from "../img/indoor.png"

export default function Projects() {
 // Sound hook
 const [play] = useSound("/sound.mp3");

  return (
    <>
      <Head>
        <title>Projects | Mohamed Sadiq</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
     
       <div className="container">
        <div className="inner_container">
          <h1>Projects</h1>
          <p>Projects I built using React, Solidity + Smart Contracts, Next.js, and TypeScript, NFT Minting</p>
         
         
          <div className="grid">
         
                <Link key={"dao"} href="">
                <div className="blocks" onClick={play}>
                  <div className='ovo developerdao_vid'>
                    <video loop autoPlay muted >
                    <source src="/u5RViMdepqRfkMte.mp4" type="video/mp4"/>
                  </video>
                </div>

                <div className="overlay"> 
                  <h2></h2>
                  <p></p>
                  <span></span>
                </div>
                </div>
                </Link>
            {data.map(item => {
              return (
                <Link key={item.name} href={item.link}>
                <div className="blocks" onClick={play}>
                  <Image
                    src={item.img}
                    alt="Picture of the author"
                    objectFit='cover'
                    layout='fill'
                    objectPosition="center"
                    quality={100}
                />

                <div className="overlay"> 
                  <h2>{item.name}</h2>
                  <p>{item.description}</p>
                  <span>{item.tags}</span>
                </div>
                </div>
                </Link>
               )
            })}
             <Link key={"ovo"} href="">
                <div className="blocks" onClick={play}>
                  <div className='ovo'>
                  <Image
                    src={"/ovovideo-3b3229df04b9ef2c3d47a36c13a5369c_Trim.gif"}
                    alt="Picture of the author"
                    objectFit='cover'
                    layout='fill'
                    objectPosition="center"
                    quality={100}
                />
                </div>

                <div className="overlay"> 
                  <h2></h2>
                  <p></p>
                  <span></span>
                </div>
                </div>
                </Link>
          </div>

          <h2>Playground</h2>
          
          <div className="grid">
            {playground.map(item => {
              return (
                <Link key={item.name}  href={item.link}>
                <div className="blocks" onClick={play}>
                  <Image
                    src={item.img}
                    alt="Picture of the author"
                    objectFit='cover'
                    layout='fill'
                    objectPosition="center"
                    // placeholder="blur"
                    quality={100}
                />

                <div className="overlay"> 
                  <h2>{item.name}</h2>
                  <p>{item.description}</p>
                  <span>{item.tags}</span>
                </div>
                </div>
                </Link>
               )
            })}
          </div>
        </div>
       </div>
      </main>

      </>
  )
}


const data = [
  {
      name:"DeveloperDAO FM",
      img:developerDaoFm,
      description:"description", 
      tags:"Product Design, JS, Web3",
      link:"/projects/developerdaofm"
  }
  ,
  {
      name:"Web 3 Lover Boy",
      img:nftweb3,
      description:"description",  
      tags:"Product Design, Solidity, Web3",
      link:"/projects/web3boy"
  },

  {
    name:"GM",
    img:gm,
    description:"description",
    tags:"Concepts",
    link:"/projects/gm"
  },
  {
      name:"Web 3 Concepts",
      img:web3cons,
      description:"description",
      tags:"Concepts, Web3",
      link:"/projects/web3concepts"
  },
  {
    name:"West World Watch Face",
    img:westworldwatch,
    description:"description",
    tags:"Apple Watch",
    link:"/projects/westworldwatch"
},
{
  name:"One-Yellow 1",
  img:nasir,
  description:"description",
  tags:"CSS, Js, Atom",
  link:"https://github.com/mohamedsadiq/one-yellow-syntax"
  }, 
  {
    name:"One-Yellow 2",
    img:vscode,
    description:"description",
    tags:"CSS, Js, Atom",
    link:"https://github.com/mohamedsadiq/one-yellow-syntax"
    }, 
    
  
    
]


const playground = [

{
  name:"Apple Watch",
  img:weatherapp,
  description:"description",
  tags:"Apple Watch",
  link:"/projects/applewatchface"
},

 

 
  {
      name:"Apple Watch",
      img:applewatch,
      description:"description",
      tags:"Apple Watch",
      link:"/projects/applewatchface"
 },
 {
  name:"Crypto App",
  img:watchcrypto,
  description:"description",
  tags:"Concepts, Web3",
  link:"/projects/cryptoapp"
},
{
  name:"Trust Wallet App",
  img:trustWallet,
  description:"description",
  tags:"Concepts",
  link:"https://www.behance.net/gallery/130411983/Redesigning-the-Trust-Wallet-App"
  },





]