import Head from 'next/head';
import Link from 'next/link';
import Image from 'next/image';
import LazyLoad from 'react-lazyload';

const sparksData = [
  {
    href: 'sparks/widget',
    title: 'Widget',
    description: 'An interactive widget.',
    date: 'June - 2024',
    type: 'video',
    src: '/dots.mov',
    mediaType: 'video/mp4'
  },
  {
    href: 'sparks/button',
    title: 'Button',
    description: 'An interactive button.',
    date: 'June - 2024',
    type: 'image',
    src: '/fffsfs.gif',
    width: 100,
    height: 100
  },
  {
    href: 'sparks/scroll',
    title: 'Scrolling',
    description: 'Widget Scrolling.',
    date: 'June - 2024',
    type: 'video',
    src: 'https://video.twimg.com/ext_tw_video/1801041108274757632/pu/vid/avc1/480x480/qbJ7cC1MrzCqk444.mp4?tag=12',
    mediaType: 'video/mp4'
  },
  {
    href: 'sparks/TheMartian',
    title: 'The Martian',
    description: 'A character on Mars.',
    date: 'Jul - 2024',
    type: 'video',
    src: '/martin.mov',
    mediaType: 'video/mp4'
  },
  {
    href: 'sparks/onhover',
    title: 'On Hover',
    description: 'On hover interaction.',
    date: 'Jul - 2024',
    type: 'video',
    src: '/Screen Recording July 11.mov',
    mediaType: 'video/mp4'
  },
  {
    href: 'sparks/gameui',
    title: '3D interactive demo',
    description: 'Smooth transitions.',
    date: 'Jul - 2024',
    type: 'video',
    src: '/July 10 Screen Recording.mp4',
    mediaType: 'video/mp4'
  }
];

const Sparks = () => {
  return (
    <>
      <Head>
        <title>Sparks</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <meta name="keywords" content="HTML, CSS, JavaScript, product design, web3, nft" />
        <meta name="author" content="Mohamed Sadiq" />
        <meta name="twitter:card" content="summary_large_image" />
        <meta name="twitter:site" content="@mosadiq.com" />
        <meta name="twitter:title" content="Mohamed Sadiq" />
        <meta name="twitter:description" content="Product designer & Engineer." />
        <meta name="twitter:image" content="https://i.ibb.co/Cvc4f6R/Instagram-post-6.png" />
      </Head>
      <main>
        <div className="container container_sparks_home">
          <div className="inner_container inner_container_spark">
            <h1>Sparks</h1>
            <p>An engineering snippets</p>

            <div className="spark">
              {sparksData.map((spark, index) => (
                <Link href={spark.href} passHref key={index}>
                  <div className="spark_block">
                    <LazyLoad>
                      {spark.type === 'video' ? (
                        <video width="100%" height="100%" autoPlay loop muted playsInline>
                          <source src={spark.src} type={spark.mediaType} />
                          Your browser does not support the video tag.
                        </video>
                      ) : (
                        <Image alt={spark.title} src={spark.src} className="buttoninter" width={spark.width} height={spark.height} loading="lazy" />
                      )}
                    </LazyLoad>
                    <div className="spark_info">
                      <div className="spark_title">{spark.title}</div>
                      <div className="spark_dec">{spark.description}</div>
                    </div>
                    <div className="spark_date">{spark.date}</div>
                  </div>
                </Link>
              ))}
            </div>
          </div>
        </div>
      </main>
    </>
  );
};

export default Sparks;
