import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Header from '../components/Header'
import Layout from "../components/Layout"
// images Wallets
import Rainbow from "../img/wallets/rain.png"
import Coinbase from "../img/wallets/Coinbase.png"
import Metamask from "../img/wallets/Metamask.png"
import Ledger from "../img/wallets/Ledger.png"
import Trustwallet from "../img/wallets/Trustwallet.png"
import Gnosis_Safe from "../img/wallets/Gnosis Safe.png"
// images Daos
import DeveloperDao from "../img/daos/Elliffpse 4.png"
import VectorDAO from "../img/daos/Ellipse 4.png"
import Fwb from "../img/daos/Elliphgse 4.png"
import Citydao from "../img/daos/Ellinhgge 4.png"
import Forefront from "../img/daos/Elligbfgbfgpse 4.png"
import Syndicate from "../img/daos/Ellipse fgsdgs4.png"

// images tools
import ValueApp from "../img/Tools/bc326de2-ce60-4102-9be1-ba654f4d8ad1.jpeg"
import Raritysniper from "../img/Tools/favicon.png"
import Snapshot from "../img/Tools/Group 122.png"
import Guild from "../img/Tools/L8tmHbzm_400x400.jpg"


export default function web3stack() {
   

  return (
    <>
      <Head>
        <title>Web 3 Stack | Mohamed Sadiq</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
   
       <div className="container">
        <div className="inner_container">
          <h1>Web 3 Stack</h1>
          <p>Here is a list of web3 tools, DAOs and Wallets.</p>
          <h2>Wallets</h2>
          <div className="inner_stack">
           
          {wallet.map(item => {
              return (
                  <div key={item.name} className="block">
                      <div className="top_block">
                        <div className="logo_stack">
                        <Image
                            src={item.img}
                            alt="Picture of the author"
                            objectFit='cover'
                            layout='fill'
                            objectPosition="center"
                            placeholder="blur"
                            quality={100}
                            />
                        </div>
                        <div className='arrow'> 
                                <svg width="35" height="35" viewBox="0 0 35 35" fill="none" xmlns="http://www.w3.org/2000/svg">
                                <path d="M33.2126 3.04953L33.2126 22.4767L35 22.4767L35 0.00128174L12.5233 0.00128076L12.5233 1.78628L31.9498 1.78871L-2.56206e-06 33.7356L1.26325 34.9988L33.2126 3.04953Z" fill="#464646"/>
                                </svg>
                        </div>
                      </div>
                      <h1>{item.name}</h1>
                      <p>{item.description}</p>
                  </div>
              )
          })}
          </div>
          <h2>DAOs</h2>
          <div className="inner_stack">
          {Daos.map(item => {
              return (
                  <div key={item.name} className="block">
                       <div className="top_block">
                        <div className="logo_stack">
                        <Image
                            src={item.img}
                            alt="Picture of the author"
                            objectFit='cover'
                            layout='fill'
                            objectPosition="center"
                            placeholder="blur"
                            quality={100}
                            />
                        </div>
                        <div className='arrow'> 
                                <svg width="35" height="35" viewBox="0 0 35 35" fill="none" xmlns="http://www.w3.org/2000/svg">
                                <path d="M33.2126 3.04953L33.2126 22.4767L35 22.4767L35 0.00128174L12.5233 0.00128076L12.5233 1.78628L31.9498 1.78871L-2.56206e-06 33.7356L1.26325 34.9988L33.2126 3.04953Z" fill="#464646"/>
                                </svg>
                        </div>
                      </div>
                      <h1>{item.name}</h1>
                      <p>{item.description}</p>
                  </div>
              )
          })}
          </div>
          <h2>Tools</h2>
          <div className="inner_stack">
          {Tools.map(item => {
              return (
                  <div   key={item.name}className="block">
                       <div className="top_block">
                        <div className="logo_stack">
                        <Image
                            src={item.img}
                            alt="Picture of the author"
                            objectFit='cover'
                            layout='fill'
                            objectPosition="center"
                            placeholder="blur"
                            quality={100}
                            />
                        </div>
                        <div className='arrow'> 
                                <svg width="35" height="35" viewBox="0 0 35 35" fill="none" xmlns="http://www.w3.org/2000/svg">
                                <path d="M33.2126 3.04953L33.2126 22.4767L35 22.4767L35 0.00128174L12.5233 0.00128076L12.5233 1.78628L31.9498 1.78871L-2.56206e-06 33.7356L1.26325 34.9988L33.2126 3.04953Z" fill="#464646"/>
                                </svg>
                        </div>
                      </div>
                      <h1>{item.name}</h1>
                      <p>{item.description}</p>
                  </div>
              )
          })}
          </div>
        </div>
       </div>
      </main>
  
</>
  )
}

const wallet = [
    {
        name:"Rainbow",
        img:Rainbow,
        description:"The fun, simple, & secure way to explore Web3, NFTs, & Ethereum."
    },
    {
        name:"Coinbase",
        img:Coinbase,
        description:"Self-custody, mobile crypto wallet and Web3 dapp browser."
    },
    {
        name:"Metamask",
        img:Metamask,
        description:"A crypto wallet & gateway to blockchain apps."
    },
    {
        name:"Ledger",
        img:Ledger,
        description:"The smartest way to secure, buy and exchange crypto."
    },
    {
        name:"Trustwallet",
        img:Trustwallet,
        description:"Buy, store, collect NFTs, exchange & earn crypto."
    },
    {
        name:"Gnosis Safe",
        img:Gnosis_Safe,
        description:"The most trusted platform to manage digital assets."
    }
]

const Daos = [
    {
        name:"DeveloperDao",
        img:DeveloperDao,
        description:"Accelerate the education of a new wave of web3 builders."
    },
    {
        name:"VectorDAO",
        img:VectorDAO,
        description:"A collective of designers making Internet money easier to use."
    },
    {
        name:"FRIENDS with BENEFITS",
        img:Fwb,
        description:"A digital cornerstone between technology and culture."
    },
    {
        name:"Citydao",
        img:Citydao,
        description:"Experiment in decentralized land ownership."
    },
    {
        name:"Forefront",
        img:Forefront,
        description:"The port of entry to social clubs and digital cities."
    },
    {
        name:"Syndicate",
        img:Syndicate,
        description:"Decentralized investing protocol + social network."
    }
]


const Tools = [
    {
        name:"Value App",
        img:ValueApp,
        description:"A simple way to track the value of any NFT portfolio in real time."
    },
    {
        name:"Rarity Sniper",
        img:Raritysniper,
        description:"The #1 source for NFT rarity."
    },
    {
        name:"Snapshot",
        img:Snapshot,
        description:"Where decisions get made."
    },
    {
        name:"Guild",
        img:Guild,
        description:"Manage roles in your community based on tokens."
    },
   
]