import { useEffect, useRef } from "react";
import Head from "next/head";
import BackButton from "../../components/backButton";
import { useRouter } from 'next/router';
import Footer from '../../components/sparksNav';
import { AnimatedSection } from "../../components/AnimatedSection";
import SparkContainer from "../../components/SparkContainer";

export default function FamilyTransactions() {
  const widgetRef = useRef(null);
  const router = useRouter();

  useEffect(() => {
    const widget = widgetRef.current;

    const handleScroll = () => {
      const scrollTop = widget.scrollTop;
      const scrollHeight = widget.scrollHeight - widget.clientHeight;

      if (scrollTop > scrollHeight / 4) {
        widget.classList.add("storm-visible");
        widget.classList.remove("rainy-visible");
        document.querySelector(".dot:nth-child(2)").classList.add("activeDot");
        document
          .querySelector(".dot:nth-child(1)")
          .classList.remove("activeDot");
      } else {
        widget.classList.add("rainy-visible");
        widget.classList.remove("storm-visible");
        document.querySelector(".dot:nth-child(1)").classList.add("activeDot");
        document
          .querySelector(".dot:nth-child(2)")
          .classList.remove("activeDot");
      }
    };

    widget.addEventListener("scroll", handleScroll);

    return () => {
      widget.removeEventListener("scroll", handleScroll);
    };
  }, []);

  return (
    <>
      <Head>
        <title>Scrolling</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    
        <SparkContainer>
          <AnimatedSection delay={0.1}>
            <BackButton title="" />
          </AnimatedSection>
          <AnimatedSection delay={0.15}>
            <h2 className="text-base text-black dark:text-white">Scrolling</h2>
          </AnimatedSection>
          <AnimatedSection delay={0.2}>
            <p className="mt-0 text-base text-[#616161] mb-4 dark:text-[#616161]">
              It's a scroll, but with a twist. Instead of the typical scroll
              bar, I integrated circular indicators to signify the moving
              content, elevating the overall user experience.
            </p>
          </AnimatedSection>
          <AnimatedSection delay={0.25} className="w-full">
            <div className="expBorder">
              <div className="exp" style={{ height: "400px" }}>
                <div className="rainy"></div>
                <div className="dotsForScrolling">
                  <div className="dot activeDot"></div>
                  <div className="dot"></div>
                </div>
                <div className="widget" ref={widgetRef}>
                  <div className="storm"></div>
                  <div className="rainy"></div>
                  <div style={{ height: "400px" }}></div>
                </div>
              </div>
            </div>
          </AnimatedSection>
          <AnimatedSection delay={0.3} className="w-full">
            <Footer currentPath={router.pathname} />
          </AnimatedSection>
        </SparkContainer>
    
   
    </>
  );
}
