import { useEffect, useRef } from "react";
import Head from "next/head";
import Script from "next/script";
import BackButton from "../../components/backButton";

export default function Widget() {
  return (
    <>
      <Head>
        <title>Widget</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="container inner_container_sparks">
          <BackButton title={""} />
          <div className="inner_container inner_container_sparks">
            <h2>Widget</h2>
            <p>
              It's a scroll, but with a twist. Instead of the typical scroll
              bar, I integrated circular indicators to signify the moving
              content, elevating the overall user experience.
            </p>
            <div className="exp flex justify-center items-center">
              <div className="w-44 h-44 rounded-3xl bg-gray-400">
                <div className="daysExercises">daysExercises</div>
                <div>
                    <span>18/28 days</span>
                    <h4>doing morning exercises</h4>
                </div>
              </div>
            </div>
          </div>
        </div>
        <Script
          src="https://www.googletagmanager.com/gtag/js?id=G-H699TZ29QW"
          strategy="afterInteractive"
        />
        <Script id="google-analytics" strategy="afterInteractive">
          {`
            window.dataLayer = window.dataLayer || [];
            function gtag(){dataLayer.push(arguments);}
            gtag('js', new Date());
            gtag('config', 'G-H699TZ29QW');
          `}
        </Script>
      </main>
    </>
  );
}
